### ISSUE TITLE
Crontab doesn't work

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#1036]
Hi,
version 3.3.0b
if in crontab I set 2 rules every 5 min it's run only the first one.
Can you replace same issue or do you have a tips?
![image](https://github.com/Myddleware/myddleware/assets/6990139/d068a7d1-8494-4666-831c-045d138c1b17)

![image](https://github.com/Myddleware/myddleware/assets/6990139/7508d945-4e32-4462-892e-afa7b6b7a78e)

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
In this case you can put 2 rules in the synchro command like this : 
`myddleware:synchro 61cad6ccdeef7,61cb43b2c9770,61cc5e6bdd92c`
![image](https://github.com/Myddleware/myddleware/assets/11330301/a57c1b8a-c08f-4f57-87f2-6bda53d22554)

Please put the ids of the rules you want to run.
Hope it helps

**Comment by simonetravaglini** [comment]
Hi @Myddleware thanks for answer.
But suppose I've this scenario.
1 - rule1 and rule2 have to run every 5 minuts
2 - rule3 have to rune one times every day
There is a way to set this scenario?
Becouse if I set rule1 and rule2 every 5 minutes and rule3 i.e. at 23.00, becouse on same cron run rule3 will not work.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You rule3 should be executed because all cron task should run. 
There is maybe a problem with your 2nd command that executes your second rule (I speak about your first post). You number of running instance is probably greater or equal you max intance, could you check your table cron_job : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/84d65e99-7d02-4e2b-8041-fe4ae1efe96b)

If you want you can increase your max number of instance.

Please let me know if it solved this issue ? 
Thanks.

**Comment by simonetravaglini** [comment]
Hi @Myddleware I've already been set max instance to high number. So it's not the issue.

Not clear to me how should works.
If I set differents crons with period 5 min it runs only the first and doesn't consider other ones?
If I set a cron every 5 min and a cron every 1440 min then both will be run at same time?

In my expectation all crons should run, also if set with same frequency, but seems it's not true...

**Comment by Myddleware** [comment]
Hi @simonetravaglini ?
Yes all crons should run. Coud you open a terminal, go to the Myddleware's root directory and run this command : 
`php bin/console myddleware:cronrun --env=background`

You should see why the task isn't executed.

Please let me know if you see something that helps us to identify the issue. 
Thanks.

**Comment by simonetravaglini** [comment]
Hi,
to resume the issue.
I've set these 2 crons:
![image](https://github.com/Myddleware/myddleware/assets/6990139/891712d8-2281-458f-8e82-52c6c87e2b38)
If we manually activate cron as requested output is:
![Screenshot from 2023-06-29 14-20-58](https://github.com/Myddleware/myddleware/assets/6990139/0648987a-f2d4-4fff-8338-e1a81fa27455)

It seems that after the first active rule is load than cron doesnt run following crons

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Thanks for this detail. We will try to reproduce this issue.
We 'll keep you posted.

**Comment by AlexMyddleware** [comment]
Hello @simonetravaglini, I found the source of your problem by comparing the results of the cron with 3.3.4 and 3.3.0b. The bug was fixed very soon after 3.3.0b but it is still there in your code. You can try to upgrade to a more recent version of myddleware like 3.3.1 or if you want to stay on 3.3.0b for now you can fix the bug yourself following this commit

https://github.com/Myddleware/myddleware/commit/d7c82bc16e10501ed6b366b23e9fad01e4c9e11c

I will mark this issue as closed for now, but if you still have an issue with this feel free to re open it.
