### ISSUE TITLE
Save the filter even if the user doesn't click on "+" button

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1127]
If we don't click on "+" button the filter isn't saved.

**Comment by AlexMyddleware** [comment]
this is now fixed. 

step 1 no filter

![image](https://github.com/Myddleware/myddleware/assets/106162060/317e7cce-7a11-4cde-b5bd-7eb0e06b4d03)

step 2 we select the date filter

![image](https://github.com/Myddleware/myddleware/assets/106162060/2b486213-6b06-4ca5-bcda-ba71dfc95149)


step 3 we go to the homepage, and we go back to the documents and hit the search button (because upon arriving on the page, we automatically have no documents)

![image](https://github.com/Myddleware/myddleware/assets/106162060/39104f32-80ba-4184-94cb-9b613885fc8b)

**Comment by AlexMyddleware** [comment]
fixed in https://github.com/Myddleware/myddleware/pull/1138

**Comment by AlexMyddleware** [comment]
fixed in https://github.com/Myddleware/myddleware/pull/1138
