### ISSUE TITLE
Invalid parameter while synchronizing data between PrestaShop and Moodle

### ISSUE THREAD

**Issue by BF-Pro** [Myddleware/myddleware#1212]
Hello,

I am facing issue with synchronizing data between PrestaShop and Moodle. After running all build-in rules i receive error that says 

"invalidparameter : Invalid parameter value detected. (users => Invalid parameter value detected. (Unexpected keys (id_doc_myddleware, source_date_modified) detected in parameter array.): Unexpected keys (id_doc_myddleware, source_date_modified) detected in parameter array.)Failed to send document. Status : Error_sending"

It seems to be problem with data sent by Myddleware to Moodle, am I correct? What should i have to change to be able to synchronize data? 

PrestaShop - 8.1.7
Myddleware - 3.3.0b
Moodle - 4.0.12

![Myddleware1](https://github.com/user-attachments/assets/e496f3b3-73c1-4c22-9dc9-f7ffd409c46a)
![Myddleware2](https://github.com/user-attachments/assets/12f7f707-e798-4789-ba2d-6dfd08739aaa)

If you need any additional information, feel free to reach out.
Regards!

**Comment by Myddleware** [comment]
Hi @BF-Pro ,
You don't have the latest version. The bug is fixed here : 
![image](https://github.com/user-attachments/assets/ba0dc612-dabb-4ae2-a742-9b740e42c981)

Could you update your Myddleware version to the 3.3.4 using this tutorial : https://myddleware.github.io/myddleware/#/admin_tasks?id=init-amp-fetch-from-github

For information, we will launch a new main version in a few weeks.

**Comment by BF-Pro** [comment]
Hello @Myddleware,

Thanks for advice! It works!

**Comment by Myddleware** [comment]
Thanks for your feedback.
