### ISSUE TITLE
ErpNext Connector not transferring.

### ISSUE THREAD

**Issue by codrotech** [Myddleware/myddleware#129]
I created a solution to connect PrestaShop(Source) to ErpNext(Target), 
I mapped all required field and when I go to run the rule no transfers are made no error either.
Right now my Erpnext is set to create the id "name" same as "item_code". 
In the list of field for the module Item "name" doesn't appear which I assume it get the value from "item_code".
Please let me know if more infos are required in oder to resolve this issue.

Thanks
Maurizio

**Comment by Myddleware** [comment]
Hi Maurizio,

I am just answering your "no transfer" quetsion. 

Did you set the reference date or your rule in the past ? 

Here is more detail about this reference date : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

If you have another problem about field mapping, could you open another issue because it seems to be 2 separated problems. Thanks.

Please let us know if it solved your "no transfer" problem ? 
Thanks.

Stéphane

**Comment by codrotech** [comment]
The issue was solved.
The reference date was set for today() it was not pulling Products from Presta(Source)

Thanks.
Maurizio

**Comment by Myddleware** [comment]
Great news.
Thanks for your feedback.
