### ISSUE TITLE
Limited Prestashop modules as target

### ISSUE THREAD

**Issue by azapater** [Myddleware/myddleware#154]
Hi,

Using Prestashop as a target just shows a few modules available. If I choose it as source I can access all the information, but as target just products, messages an a few more. I assume after checking the code that it's the only information available as a target, so I was wondering if more modules will be added, such as stocks. 

I wouldn't mind to try to code it by myself, but TBH the code it's quite deep and complex, so I'd need some guidelines first. 

Thanks

**Comment by Alexandre17220** [comment]
So you want modify stock on Prestashop.
Maybe, first, you can do it directly via webservice in Prestashop.
And second create your own module in myddleware based on your update stock script. The source code of myddleware is clean and comprehensible for developper, I think.

**Comment by Myddleware** [comment]
Hi,
You are right, we have put just a few modules as target. You can try to add the modules you need in the array $authorized (file  : myddleware\src\Myddleware\RegleBundle\Solutions\prestashop.php)
![image](https://user-images.githubusercontent.com/11330301/54614953-a693c380-4a33-11e9-919f-e512955aaf25.png)

It could simply work without doing anything else because we tried to made a code as dynamic as possible. We didn't add more module because we didn't test them.
 
So if it works fine with other modules, could you tell us which modules or just commit your file on our project as a contributor (hotfix branch).

If it doesn't work, we will definitely help you. Just tell us what error you get (probably in the create ou update method in the Prestashop class).

Please keep us posted.
Best regards,
Stéphane

**Comment by Myddleware** [comment]
Hi Alexandre,
Thanks for your reply, we have written in the same time ;).
Have a nice day.

**Comment by Alexandre17220** [comment]
Hi Stéphane,
Thanks again for your great solution, very strong, I love ETL with myddleware 👍 
have a nice day

**Comment by Myddleware** [comment]
Thank Alexandre for your feedback 👍

**Comment by azapater** [comment]
Thank you very much for your replies. I'll play around with your suggestions and if I eventually add anything (and I test it in production), I'll commit the modifications.

**Comment by Alexandre17220** [comment]
@azapater be carefull with PS you must modify stock AND historize it, PS don"t do it automaticaly.. it's very strange idea from PS team

for modify stock : 
`
function modifier_stock_produit($webService,$id_ps_produit,$quantite) {
	$opt['resource'] = 'products';
	$opt['id'] = $id_ps_produit;
	$xml = $webService->get($opt);
	//(les "stock_availables ont créé automatiquement par PS à l'insert du produit précédent)
	foreach ($xml->product->associations->stock_availables->stock_available as $stock) {

		$xml2 = $webService->get(array('url' => PS_SHOP_PATH . '/api/stock_availables?schema=blank'));
		$stock_availables = $xml2->children()->children();
		$stock_availables->id = $stock->id;
		$stock_availables->id_product  = $id_ps_produit;
		$stock_availables->quantity = $quantite;
		$stock_availables->id_shop = 1;
		$stock_availables->out_of_stock = 1;
		$stock_availables->depends_on_stock = 0;
		$stock_availables->id_product_attribute = $stock->id_product_attribute;

		//POST des données vers la ressource 
		$opt = array('resource' => 'stock_availables');
		$opt['putXml'] = $xml2->asXML();
		$opt['id'] = $stock->id ;
		$xml2 = $webService->edit($opt);
	}
}
`
I let you find for historize it 

have a nice day

**Comment by azapater** [comment]
thanks @Alexandre17220 That's going to be very useful. After doing some research I'm realising (as you point out) that syncing stocks is not as simple as just update the table. 

thanks again

**Comment by Alexandre17220** [comment]
never update table directly, you must use webservice or PS object , because hook system
