### ISSUE TITLE
Simple Moodle to Hubspot rule fails

### ISSUE THREAD

**Issue by renehamburger** [Myddleware/myddleware#155]
I'm using Myddleware for the first time today. I've been able to set up connectors to Moodle and Hubspot without issues. The respective connection tests as well as the rule simulation show that both connectors work.

But a very simple rules to sync users either from Moodle to Hubspot or vice versa fail with the error message "Failed to get the task id", which is triggered by the exception thrown [here](https://github.com/Myddleware/myddleware/blob/6708c27573a3c14460d6fecadda55990ea357ae6/src/Myddleware/RegleBundle/Classes/rule.php#L878). The log file prod.log does not contain any details. The simulation during rule creation displayed valid data.

Any ideas what could be going wrong here?

With another rule to sync a Moodle course to Hubspot I didn't even get that far. The simulation yielded no results, but the error message "There is no data in the source server or fields in the target solution", even though there are two courses in my Moodle system. I have installed the plugin, even though it shouldn't be necessary for this, and double checked the webservice functions activated for this service. 'core_course_get_courses_by_field' is included, for example.

**Comment by Myddleware** [comment]
Hi,
Thanks for using Myddleware.

About your first problem : "Failed to get the task id". You try to run Myddleware task from your browser, in this case we save the task id in the directory myddleware\var\cache\prod\myddleware\job . Could you make sure this directory exists and your web user (generally httpd or www-data) have the right tp create it and to write into it ? If yes could you check if there are some files in this directory ?

However, I advise you to use background task to run Myddleware. You can set up ths scheduler with a cron task, here a tutorial to help you : https://myddleware.github.io/myddleware/#/cron_jobs
You can alse run drectly you rule by sendind this command from Myddleware root directory : 
`php bin/console myddleware:synchro <YOUR_RULE_ID> --env=background`
These processes won't use cache directory to save task id. 

About your second problem, you are right, the rule simulation use the function core_course_get_courses_by_field. But we add a parameter time_modified. By defaut and only for simulation purpose, we search course modified after today - 1 year. You can change it by modifying the class attribut delaySearch.
So if your courses haven't been modified for more than 1 year, it is expected that you have no result. Otherwise you should have a result. If it is the case, could you open a new issue on this forum for this specific problem ? Thanks.

Have a nice day,
Stéphane

**Comment by renehamburger** [comment]
Thanks for the swift response, Stéphane!

Yes, the txt files are created in that directory, but they are empty. I debugged the code and when I execute the shell command in that function manually, it _does_ return the expected output. I'm not sure why it wouldn't work through `exec()`!

I wanted to wait with activating the cron job until I got it work.

When I execute the command manually as you suggested (` php bin/console myddleware:synchro 5c94f1d7a492b --env=background`), I'm actually getting two errors:
```
In BaseNode.php line 319:
  Invalid configuration for path "monolog.handlers.main": Warning: count(): Parameter must be an array or an object that implements Countable

In Configuration.php line 628:
  Warning: count(): Parameter must be an array or an object that implements Countable
```
When I use `prod` instead of `background`, the sync seems to complete, but no documents are created:
```
1;5c94f265a5e997.84493021
5c94f1d7a492b
Read data for rule : 5c94f1d7a492b
5c94f1d7a492b : Create documents.
5c94f1d7a492b : Number of documents created : 0
```

This corresponds to the "Estimated transfers" in the "Parameters" tab. But it doesn't match the data. The rule is very simple and does not use filters or relations. There are plenty of users in the system and the simulation shows the first one.

Concerning the second issue, one of the courses was only created a few weeks ago, so that can't be the issue. I'll create a separate issue for this later on.

I'm using PHP 7.2.16 and the latest version of Myddleware.

**Comment by Myddleware** [comment]
Thanks for all of these details.

If "prod" environment works and not the "background" one, it is maybe because the log or cache file can't be written. If you want to use the background environnement, it should work if you remove the directory myddleware\var\cache\background and the file myddleware\var\logs\background.log. Then make sure the system user you use can create it again.

About the fact that you didn't get data, it is probably because of your reference date on your rule. You have to put it far in the past if you want that Myddleware reads old data. Here are more info about it : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters
Please let me know if it solves your problem.
Stéphane

**Comment by renehamburger** [comment]
Thanks for your response. Let me start numbering the issues to make it easier for us to reference them.

### 1. Empty sync set

Yes, you’re absolutely right! This was due to the reference date which is set to the beginning of the day the rule is created by default. A few thoughts about this:

The parameter tab is actually quite hidden. It would be good to include at least the reference date in the process of creating a rule (or set it to 1970 to start with) or make it visible in the list overview. Most new users like me would create a rule and then run it, without realising that there are more parameters that can and should be set. (To be true, there is a sentence about this in the tutorial (“This process is based on the reference date that you can set up.”), but the importance of this isn’t clear.

I did try out changing the reference date before I filed this issue, but I didn’t realise that the simulate would not use the form fields directly, but would require a save. Disabling the “Simulate” button after a parameter change until the new parameters have been saved would be an easy way to resolve this, or showing a message next to the button.

### 2. Hubspot sync updates existing item rather than creating new items

I’m not sure whether I configured something wrongly or whether it’s a bug: The sync executed for 91 items, but rather than creating 91 new items, it changed the 3 given fields 91 times on the one pre-existing item! The field `email` was used to avoid duplicates and the mode is ‘Create and update data’.

I created the same rule again with other fields, using email again as the identifier and the same happened again.

When I delete the single item from Hubspot, all transfers result in errors. Here’s one example:

Id | Reference | Job | Date of creation | Type | Message
-- | -- | -- | -- | -- | --
2994 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:49 | E | Failed to create data in hubspot. resource not foundFailed to send document. Status : Error_sending
2904 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:29 | S | Status : Ready_to_send
2814 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:11 | S | Status : Transformed
2724 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:10 | S | Status : Relate_OK
2632 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:10 | S | Status : Predecessor_OK
2631 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:10 | S | Target id : 101
2630 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:10 | S | Type : U
2363 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:09 | S | Status : Filter_OK
2272 |   | 5d95f37c117049.53894825 | 23/03/2019 08:51:09 | S | Status : New

There was one error that occurred during the sync for each item, but I don’t think this caused the issue:

```
statut Ready_to_send id = 5c95f37d21f650.47356901  2019-03-23 08:51:29
PHP Notice:  Undefined index: properties in myddleware/src/Myddleware/RegleBundle/Solutions/hubspot.php on line 999
```

### 3. Issue with background sync

I shouldn’t actually try to tell from the warnings above whether the background sync works or not. These same warning is shown when executing `php bin/console cache:clear -e prod` and after all it’s a warning and not an error:
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in myddleware/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628
```
But as `php bin/console myddleware:synchro 5c9526af41f6f --env=background` doesn’t add any new transfer items, it doesn’t look like it’s working. Or is there any other way to tell? No background.log file has been created in var/logs, but var/cache/background/appBackgroundDebugProjectContainerDeprecations.log was created.

The folder permissions are fine. I even reinstalled Myddleware once again to be sure everything is in the state it should be in.

### 4. Change of MySQL password

Another, unrelated issue which I hadn’t mentioned before was this: I changed the MySQL password but it didn’t propagate. Emptying the folder var/cache did the trick. I’m just mentioning this here so others can find it.

### 5. Unable to create rule for Moodle course sync

I will create a new ticket for this now.

**Comment by renehamburger** [comment]
I should add the issue I mentioned initially here, too:

### 6. Executing all active rules yields the error "No task id given."

See above for more details. This issue also occurs when trying to cancel transfers with errors. So it is not currently possible to cancel errors (or edit rules with transfer errors) through the UI.

**Comment by renehamburger** [comment]
Brief feedback concerning "3. Issue with background sync":
When I use php v7.1.27 instead of v7.2.16, I don't get those warnings and the background sync continues in the same way a sync for `--env=prod`.

This version of php does, however, still run into the other issues I mentioned above.

**Comment by renehamburger** [comment]
I found out the reason behind '6. Executing all active rules yields the error "No task id given."'! The asynchronous execution of the task used the default php executable, which pointed to php v7.0.33 in my case. I had set php to 7.2 for the domain, but also needed to adjust the executable in `parameters_public.yml` (and emptied the cache directory).

Would it be worth checking the version of this executable before using it? Or maybe mention in connection with the minimum requirement of php 7.1 that setting the version on the domain may not be enough, if `php` points to a different version.

I am now able to cancel transfers. Unfortunately, the "Execute all active rules" (issue 6 above) now encounters a different error: "Failed to run the task." There's no entry in the log to indicate why.

Issue 2 is also not resolved through the update of the php executable. The `Undefined index ...` error message is now gone, but executing the rule via the command line is still not able to sync any contact to Hubspot. Why is it trying to find a resource for a contact if it should be created as new? Do you think it would be worth emptying the database again and creating the rule again?

**Comment by Myddleware** [comment]
Thanks for all your feedback and all the time you spend on Myddlewar. It is very usefull.

Next time could you crate a issue for each point. I will be easier to manage. Thanks.

Here are my answers : 

1. Empty sync set
	Thanks for this, we will change it in the version.
	
2. Hubspot sync updates existing item rather than creating new items
	Could you create another issue for that please ? When you cerate it, could you give me more info about you rule (source and target module and if you set a relationship or not).
	
3. Issue with background sync
	Thanks for your feedback.

4. Change of MySQL password
	You are right, you have to clear the cache when you change myddleware 's database parameters. Thanks for your feedback.
	
5. Unable to create rule for Moodle course sync
	Thanks for this new issue. 
	
6. Executing all active rules yields the error "No task id given."
	You are right, we should test the php version when we run the exec function. We will take care of it.
	
We will continue to talk about the issue 2 on this thread.

**Comment by Myddleware** [comment]
So let's talk about the issue 2. 
You try to read users from Moodle and send them to hubspot, isn't it ? 
If yes, do you have a result when Myddleware try to read users from Moodle ? I need to know if Myddleware can read users from Moodle or if the problem happens after that ?
Thanks.

**Comment by renehamburger** [comment]
I reinstalled Myddleware and recreated the rule again and this time it worked.

Only the first item couldn't be synced: the default Moodle guest user, which has the invalid email address "root@localhost". Maybe this was the reason why things went wrong the first time or it was due to using php 7.0 inadvertently.

The execution of all active tasks through the UI now also works miraculously.

Thanks for your support!
