### ISSUE TITLE
Behaving slow

### ISSUE THREAD

**Issue by sagaraspl** [Myddleware/myddleware#182]
Hi @myddleware-dev 

It is taking really big amount of time. For e.g. to process 5000 thousands records it is taking around 1.5 hours so if I have let us say really big database, I think this will then turn into days to run the migration process.

Do you have any performance statistics?

**Comment by Myddleware** [comment]
Hi @sagaraspl ,

Do you mean 5 000 record or 5 000 thousand of records ? 

Do you try to process all of these records in one Myddleware task ? Or do you use several task reading less  data but more often ?

Best regards,
Stéphane

**Comment by sagaraspl** [comment]
Hi @Myddleware 

Sorry for wrong figures and thanks for reply. Yes I mean just 5 thousands (5,000) and it took 1.5 hour then I tried to divide it into say 1 thousand each (1,000) and it took 1 hour so that is also slow.

So do you have any benchmark that based on xyz resource (i.e. HDD, memory, processor) etc... it will take x amount of time to process y number of records?

This will help us to calculate that how long it will take for larger database. As I have the source database which have million of rows.

**Comment by Myddleware** [comment]
Hi @sagaraspl ,

1000 records take usually between 5 and 10 minutes to be read and send by Myddleware. it depends of the complexity of your rule, specially the number of relationship you have and the number of data already send by Myddleware.. 

To check what is going on, you can run a rule manually in a command like putty. Run this command from Myddleware root directory: 
` php bin/console myddleware:synchro <id of  your rule> --env=background`

Then you will be able to see which stage takes the more time. If it is the "new" status stage then the performance issue comes from your source application.  If it is the "send" status stage or "ready_to_send" status stage then the performance issue comes from your target application. Otherwise the performance issue comes from Myddleware, in this case could you tell me which stage status takes the more time (relate, predecessor...)

Thanks
