### ISSUE TITLE
Sales Invoices status "Paid" is not working in ERPNext

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#205]
I am sending a Sales Invoice to ERPNext containing the following:
- Customer
- Sales Invoice Items
- Sales Invoice Payment (Version 12)
- _status_: "Paid"

All are sent into ERPNext but still in **Draft status**. How can these be submitted by default?

Right now I have to go to ERPNext and:
- Press _Submit_
- Alter "Are you Sure you Want to permanently submit?" I press _Yes_.

**Comment by dawoodjee** [comment]
@myddleware-dev @Myddleware 

Any idea why this status is not working?

**Comment by Myddleware** [comment]
@chdecultot, do you know why we can't set the status Paid using the API for invoices in ERPNext ?

**Comment by dawoodjee** [comment]
I'm using ERPNext V12.

I've noticed Sales Invoice status is called status in Myddleware but
defined as docstatus when scripting in ERPNext. Don't know but this might
be something

**Comment by chdecultot** [comment]
Hi guys,

The paid status in ERPNext is determined based on the outstanding amount in the invoice document.
So you either need to send the corresponding payment to ERPNext after the invoice or you just artificially set the field "outstanding_amount" to 0 when sending your invoice (not a clean option though...)

docstatus and status are two distinct fields in ERPNext:
- docstatus handles the status of the document: draft, submitted, cancelled. It is a technical field.
- status, when exists, handles the functional status of the document: not paid, paid, overdue....

In any case, your sales invoice must be submitted for the status to be fetched, meaning that the "docstatus" field must be set to 1 first.
When developing the integration, we didn't request the Myddleware team to add the docstatus in the list of fields accessible through the API, because I prefer to use ERPNext's hooks in order to trigger all validations on ERPNext's side during the submission process. But that is certainly something that can be added: just add the "doctstatus" field in the API and set it to 1 to automatically submit your document when sending it to ERPNext.
Then, if you send the payment with the correct links between documents, the status will be updated automatically to "Paid".

**Comment by bhaktaraz** [comment]
**Working sample data to create 'Sales Invoice' through ERPNext Rest API** 

`$salesInvoiceData = [
                "docstatus" => 1,
                "customer" => "Test Customer API",
                "due_date" => date('Y-m-d'),
                "is_pos" => 1,
                "update_stock" => 1,
                "items" => [
                    [
                        "item_code" => "SUNSCN_0001",
                        "qty" => 1,
                        "rate" => 950
                    ],
                    [
                        "item_code" => "PUPBRA",
                        "qty" => 1,
                        "rate" => 850
                    ]
                ],
                "payments" => [
                    [
                        "mode_of_payment" => "Cash",
                        "amount" => 1800,
                        "account" => "Cash - ZT",
                    ]
                ]
            ];`
