### ISSUE TITLE
custom profile fields created in moodle that need to link with salesforce

### ISSUE THREAD

**Issue by VirasatSolutions** [Myddleware/myddleware#218]
I want to connect my moodle site with salesforce but i don't know how to make rules.. i tried to make a rule (connect users from moodle to clients in salesforce) but i am not getting anything in salesforce even data is displaying in transfers tab in myddleware.

Also i want to send custom fields data from moodle to salesforce but bit there is no option to link custom fields data with salesforce in myddleware. Please check the attached image below (custom profile fields created in moodle that need to link with salesforce)

![profile custom fields](https://user-images.githubusercontent.com/46476772/65951359-88386700-e45d-11e9-9e3f-b61773de1d7b.PNG)
![screencapture-52-56-147-203-lmsdev-user-profile-php-2019-10-01-14_52_53](https://user-images.githubusercontent.com/46476772/65951367-8d95b180-e45d-11e9-9199-5906361e0178.png)

**Comment by Myddleware** [comment]
Hi @VirasatSolutions ,
Could you send us some screenshot of you data transfer in Myddleware please ? 

About your second problem, could you create another issue as it is a different subject.  Moodle custom fields aren't automatically detected as there is no webservice to retrieve the field list like in Salesforce. So a development is necessary.

**Comment by VirasatSolutions** [comment]
Let me understand you...
When user registered in moodle after cron run from myddleware user(client/contact) also registered in salesforce. Now user enroll in a course in moodle after cron run from myddleware user should also enroll in salesforce.

Now let suppose the registered user id is 1309 in moodle and after cron run user is created in salesforce and the id is a1A0J000008rWN9UAM Check the attachment below :---
![screenshot-localhost-2019 10 03-11_46_01](https://user-images.githubusercontent.com/46476772/66103435-652fc380-e5d3-11e9-9b8a-ea7e4bed6f75.png)

Now the second time i want when same user enroll into any course in moodle should also enroll in salesforce But the issue is i don't understand how i do it ? How system understand the synchronization is for this current user.
Please guide me how can i make correct relationship between these. What is the use for the relations tab in myddleware (attached image below)
![screenshot-localhost-2019 10 03-11_51_27](https://user-images.githubusercontent.com/46476772/66103749-4bdb4700-e5d4-11e9-84b8-0b6a7c2e5a3a.png)

**Comment by Myddleware** [comment]
Hi,
You are right, relationship isn't easy to understand the first time. 

You already have cretaed you first rule for the user. You have to create a second rule to send your courses from Moodle to Salesforce (in a custom module for example). Then you have to create a third rule which will read the enrolment and send them to Salesforce (in a custom module for example which will be link to the contact et the course in Salesforce). This third rule will have 2 relationship whith the first and second rules.

I said that you could use custom module for course but maybe you could use a standard one which have a one-to-many relationship with your contact module (if you use Salesforce contact module to send your Moodle users). One-to-many because sevral users can be enrolled to one course.

You can use this tutorial as an example if you want to understand a bit more Myddleware relationships : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-details

You can also see a template we have created between Prestashop and Moodle using the same logic you want to set up except that Moodle is the target application in this template. But it could help you to understand how to use relationship. the template is in this file : https://github.com/Myddleware/myddleware/blob/master/src/Myddleware/RegleBundle/Templates/prestashop_moodle_user_enrolment_course.yml

Hope it will help you.
