### ISSUE TITLE
Filtered Transfers

### ISSUE THREAD

**Issue by rafaelsgritti** [Myddleware/myddleware#224]
When a transfer is filtered, it will only be loaded again if it changes? Because sometimes the orders on Prestashop are set in a Status (processing) and quickly change to another status (paid), so Myddleware filter them, because I set it so nobody have access if the order is not paid. But sometimes the filtered order is not loaded again if I don't change the status manually again.
Any way to get over this? To reload filtered transfers in a period?

Thank you for your help

**Comment by Myddleware** [comment]
Hi @zagalux,

New data will be read each time the background task of Myddleware runs. It doesn't depend on the status of the previous data transfer created for your order.

Here is what should happen : 
 - The status of your order changes to "processing"
 - Myddleware runs and reads the order. The data is filtered
 - The status of your order changes to "paid"
 - Myddleware runs and reads the order. The data is sent to your target application
 - The status of your order changes to "delivered"
 - Myddleware runs and reads the order. The data is filtered. However you order exists in your target application because it was previously sent.

You can have a problem if someting like this happens : 
 - The status of your order changes to "processing"
 - Myddleware runs and reads the order. The data is filtered
 - The status of your order changes to "paid"
 - The status of your order changes to "delivered"
 - Myddleware runs and reads the order. The data is filtered and you order doesn't exists in your target application because Myddleware didn't run between status change "paid" and  "delivered"

To avoid this kind of problem, you can run the backgroup job which read data more often.

Hope it will help.

**Comment by rafaelsgritti** [comment]
But in my case there's only 2 status, after reaching the Paid status the order doesn't change anymore. So it means that even if the time between the data read is bigger it should always read it as paid right?

**Comment by rafaelsgritti** [comment]
It will always read data? It changing or not?

**Comment by Myddleware** [comment]
Yes it will always read data if the reference date of your data has changed in the source application. 
In the rule parameters, did you selected "create data only" or "create and modify data". 

In your case you should select "create and modify data" because you want Myddleware takes the modification date_of the order as the reference date and not the creation date.

If Myddleware takes the creation date then the record will be read only after creation and not after each modification.

Please let me know if I am not clear.

**Comment by rafaelsgritti** [comment]
You're clear. There's only one more thing that I want to know, If the creation time is one second different to the next status change it'll read it normally? 
Because it is set to create and update data, but sometimes if I don't change the order state again manually it doesn't read it again. even if it first was processing and then quickly changed to paid.

**Comment by Myddleware** [comment]
If the field date modified of the order changes, then the order should be read again. 

Are you sure that the process which changes the status of your order changes the date modified of the order too. 
For example, it the status is directly changed into the database without using Prestashop framework then the date modified field  is probably not modified.

**Comment by rafaelsgritti** [comment]
I'm sure it's being modified normally, because in 90% of cases it works. So I'm not sure what's exactly happening

**Comment by Myddleware** [comment]
Just a thought. 
Maybe that in 90% of the time, your order is created and passed in status paid before Myddleware run. in this case Myddleware detects the new order. 

And maybe in 10% of the time, Myddleware runs between the order creation and the status modification to paid. in this case, if the status paid isn't made using Prestashop framework, it is possible that the order modification date doesn't change, so Myddleware won't read it again.

Could you just test it. Create a order, check the modification date in the database. then change the status to paid using your specific process (not using the status modification in Prestashop) and check again if the order modification date has been updated.

I said that because Presatshop connector is used in many Myddleware instances without any bug like that. We have done a project with several million of data read from Prestashop without missing data.

**Comment by rafaelsgritti** [comment]
I'll lookup to this.

 Thank you for your help!
