### ISSUE TITLE
SuiteCRM Contacts to Moodle Users integration error

### ISSUE THREAD

**Issue by thewebsitefactorylondon** [Myddleware/myddleware#24]
Hello,
First of all thanks very much indeed for creating such application/interface to integrate SuiteCRM to Moodle. I've successfully integrated SuiteCRM and Moodle with Myddleware (under Connectors); the problem is after I create the rule to transfer SuiteCRM contacts to Moodle Users - I get a message saying the record is created successfully, but when I browse the list of users in Moodle, I don't see any user. Furthermore, I see the following error in Transfer Lists modlule "The CSRF token is invalid. Please try to resubmit the form." Please suggest what am I missing here?
Your help will be much appreciated.
Thank you!
InfotechSyndicate

**Comment by Myddleware** [comment]
Hi, 
Thanks for your feedback. 
First of all, "The CSRF token is invalid. Please try to resubmit the form." is a known problem. It doesn't change the result of the search. It isn't linked to your problem. We will fix it shortly. Thanks.

Can you tell me if you have at least one reult when you search data transfert with no filter in Myddleware:
![search_data_transfer](https://cloud.githubusercontent.com/assets/11330301/25797836/c24f0898-33d6-11e7-958f-b23f5b0f03ac.png)
 
If yes and if its status is "send" so it confirms that a user as been send to Moodle. So you can check in the moodle database if this user is present in the table user. If yes, maybe the user wans't correctly created (fields could be missing in the Myddleware's rule for example). 

If you don't have any data transfer in Myddleware, maybe you didn't put the reference date far enough in the past, so Myddleware couldn't read any data in your CRM. Here are more explanations about the reference date : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

Please answer my questions and I will be able to help you more. 
Have a nice day,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Thank you very much for your prompt reply.
Re CSRF Token, thanks for letting me know, I though I didn't configure Moodle properly, thank God it wasn't!
Thanks for sharing the link, I followed all steps as suggested, but unfortunately no luck so far, Maybe I'm missing something. Please see the error below;
![image](https://cloud.githubusercontent.com/assets/28488395/25803957/6254f496-33f1-11e7-924e-aca03fdc786a.png)

**Please see the following for full info on error;**

![image](https://cloud.githubusercontent.com/assets/28488395/25804192/65944a5c-33f2-11e7-906a-73b9ad8a37d1.png)

Please let me know! Your help will be much appreciated.
Thank you!
InfotechSyndicate

**Comment by Myddleware** [comment]
Hi,
Sorry, there is a mistake in the tutorial here : https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle
The funtion core_user_get_users is missing, can you add it : 
![capability_get_users](https://cloud.githubusercontent.com/assets/11330301/25804918/79bd5822-33f5-11e7-9052-be4dd94608fc.png)

Could you let me know if your problem is solved ? 
Thanks

**Comment by thewebsitefactorylondon** [comment]
Hi,
Thanks again for your quick response. I tried with your suggestions, and it worked!!
However, it worked only without checking any duplicate email and username in Moodle. When I select these options and run the test, it gives me following error:

Error : Error accessexception : Access control exception MyddlewareRegleBundleSolutionsmoodlecore Line : ( 392 )Failed to search duplicate data in the target system. This document is queued. MyddlewareRegleBundleClassesdocumentcore Line : ( 828 )Status : Error_checking

![image](https://cloud.githubusercontent.com/assets/28488395/25808986/9e04d65c-3403-11e7-8976-857bc6308adb.png)


Maybe I'm Missing something here?
Once again thank you so much for your help!
Kind regards,
Infotech Syndicate

**Comment by Myddleware** [comment]
Thank you very much for your feedback.
We will analyse this access problem by checking it in our environments. However if we have to deliver a fix, it would be in the next release in 2 weeks. 
Can you use Myddleware without the fix... so without searching duplicate data in Moodle ? 

Best regards,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Once again thank you very much for your reply. Sure, I can use Myddleware without the fix for time being. Really appreciate your help and continued support. It would be a good idea to have a default template to select when we create the rules between SuiteCRM and Moodle (i.e. SuiteCRM Contacts to Moodle Users |  SuiteCRM Products to Moodle Courses | SuiteCRM Products Category to Moodle Courses Category etc.) This will be much easier for users like me.
I look forward to get a new release when it is available in two weeks time.
Thank you so much for your help and continued support!! :)
Kind regards,
Infotech Syndicate

**Comment by Myddleware** [comment]
Thank for these feedback, it helps us to improve Myddleware.

We plan to add a fonctionality in the next 6 month to allow people to share the rules they have created. So if someone create rules inhis Myddleware, he will be able to share these rules, and other Myddleware users will be able to upload these rules in their own Myddleware.

So we should have a lot of template available.

We will notify you on this ticket when we release the fix for the Moodle duplicate search.
Best regards,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
That would be great to have such feature!! Please do let me know when the bug is fixed.
Thank you!
Infotech Syndicate

**Comment by Myddleware** [comment]
Hi,
After more tests, we saw that another function was missing in the tutorial. Sorry for that. Please can you add the function core_user_update_users in your external service. 
We have updated the tutorial here : https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle

Another thing : when you add 2 parameters in duplicate search (username and email in your example), the search will be a AND. So a duplicate data will be found only if email and username are the same. Maybe it would be better to search existing users by email only.

Best regards,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,

I hope you are well and sorry for the delay in getting back to you. Many thanks for letting me know about new changes, I made these changes and tried again, unfortunately, it came with the same error;

_Error : Error accessexception : Access control exception MyddlewareRegleBundleSolutionsmoodlecore Line : ( 392 )Failed to search duplicate data in the target system. This document is queued. MyddlewareRegleBundleClassesdocumentcore Line : ( 828 )Status : Error_checking_

Also, one more question: do I have to manually update the Rule every time I create the record in SuiteCRM, or does it do automatically? So far I did manually. Please let me know.

Once again many thanks for your continued support :) 👍 

Kind regards,
Infotech Syndicate

**Comment by Myddleware** [comment]
Hi,

I am very sorry for the delay of my answer. We were working hard on the new version (2.2.1) of Myddleware. We will be more reactive now. By the way you can download it on our website or upgrade your actual Myddleware by following this tutorial : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware

It seems that your problem is on Moodle side. So if you want to test again you don't have to change the rule in Myddleware. You just have to reload the data transfert in error, you can see more details here : https://myddleware.github.io/myddleware/#/basic_usage?id=handling-documents-in-error

So now we have to find where is the permission problem in Moodle. If you go to the manage token link you can see the user linked to your token : 
![user_token](https://cloud.githubusercontent.com/assets/11330301/26193596/0eb3b72e-3bb6-11e7-9ecd-01fbf08a30a5.png)

Does this user have the right capabilities : 
![functions_capabilities](https://cloud.githubusercontent.com/assets/11330301/26193613/19993f42-3bb6-11e7-81a9-ffd3760f9b69.png)

Could you follow this tutorial as well : https://docs.moodle.org/24/en/Using_web_services

After you change you configuration in Moodle, you can reload you data transfer in error and see if the data transfer is send to Moodle or if the error message changed.

Please, keep me posted. Thanks.
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Sorry, for the delay in getting back to you. Thank you very much for your reply with full instructions. 
I'll follow them and get back to you shortly!
Kind regards,
Infotech Syndicate
