### ISSUE TITLE
[Prestashop] Product ID

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#270]
Hi.
I have some product in Prestashop before i start to use Myddleware. Myddleware create a new product with a new IDproduct. There is a possibility that myddleware update the produtc if the reference exist in prestashop?

**Comment by Myddleware** [comment]
Hi @z3n4j ,
We have added name and ean13 fields as duplicate fields. Myddleware is now able to search existing product into Prestashop before creating it. You can see the fix in this commit : https://github.com/Myddleware/myddleware/commit/ffc1e0080916f2885bfdc8322b9d1050d27525db.
 
The fix is in our hotfix branch, you can update your own Myddleware instance by modifying manually this file : 
![image](https://user-images.githubusercontent.com/11330301/75665273-372ed800-5c74-11ea-8564-e7b7689bb7ea.png)
The hotfix branch will be merged into Master branch only at the end of this week.

Then you will be able to select one of these field to check if the product already exists in Myddleware. The selected field has to be mapped (will be display in blue, not red, if you click on it), here is an example with ean13 field that I have mappend with the course idnumber : 
![image](https://user-images.githubusercontent.com/11330301/75665690-da7fed00-5c74-11ea-8beb-aa5e12f80d0f.png)
![image](https://user-images.githubusercontent.com/11330301/75665752-f4213480-5c74-11ea-9b5b-53a5ed020486.png)

Let me know if you need help.

**Comment by z3n4j** [comment]
Thank you very much. Can you add reference field as duplicate fields. I will wait end of week for upgrade myddleware.

**Comment by Myddleware** [comment]
Hi @z3n4j 
We have added the reference field as duplicate fields. 
Have a nice day.

**Comment by z3n4j** [comment]
Thank you.
