### ISSUE TITLE
Pimcore

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#271]
Hi.

Maybe you are planning to create a connector for PIMCORE?

**Comment by Myddleware** [comment]
Hi @z3n4j ,
We haven't planned to develop this connector yet. 

If you are a developper, you can try to develop it by yourself by following our tutorial : https://myddleware.github.io/myddleware/#/dev_guide
We can help you and you could contribute to Myddleware project by adding your code into Myddleware project.

Otherwise, we can develop it for you. In this case, please contact us directly here : http://www.myddleware.com/contact-us

**Comment by z3n4j** [comment]
I will see in the future for developing.
