### ISSUE TITLE
after Relate_ok  run is blocked

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#294]
I'm trying to run a rule, everything seems ok but now nothing is happening and no error:
![image](https://user-images.githubusercontent.com/6990139/79420871-0c95a600-7fba-11ea-854e-3b5290fd8b9c.png)

Seems that after STATUS: Relate_OK nothings happens.
Any idea?

**Comment by Myddleware** [comment]
Hi Simone,
If your data transfer are locked in relate_OK status, it is probably because one of your formula in your rule generate a fatal error. So the status “transformed” can’t be set.

Could you check your formula in your rule ? To be sure your formula is working, you can edit your rule and simulate it. You should have a result. If you have no answer in the simulation it means that there is an error in your formula. 
![image](https://user-images.githubusercontent.com/11330301/79439670-68b9f380-7fd5-11ea-8f77-5c826b634a68.png)

We plan to work on this kind of error to display more detail about it.

**Comment by simonetravaglini** [comment]
I confirm there was something missing in rule formula.

**Comment by Myddleware** [comment]
Perfect, thanks for your feedback.

**Comment by Myddleware** [comment]
We have developped a fix to display the error when a formula is invalid. https://github.com/Myddleware/myddleware/commit/de90f22e0e443e068a496768c8b094d9efc5ad9f
