### ISSUE TITLE
Question about delete record in Vtiger

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#297]
Hi one question:
suppose I create a connector between oracle and vtiger
Then I transfer record
Then I delete some record in vtiger
Next time i run the transfer record are not created again
There is a way to manage this situation?

**Comment by Myddleware** [comment]
In your case, the problem is that Myddleware has already created the record in Vtiger. So Myddleware will then always try to update the record not create it again. 

You have removed the record in Vtiger, and if you transfer the data transfer again, Myddleware will try to update a record which doesn't exit in Vtiger. So the record won't be created again.

If you want Myddleware to create the record again, you have to remove or cancel all data transfer corresponding on that record in Myddleware.
But it isn't possible to cancel data transfer already sent using Myddleware UI (for now, because we are preparing a super admin role which will have this right). The only way to remove or cancel data transfer already sent is to use this command in a shell prompt : myddleware:massaction

You can use the documentation of the API to learn about all the parameters : https://myddleware.github.io/myddleware/#/api?id=apimass_action

Please let me know if you need more help.
