### ISSUE TITLE
Issues tranferring data from moodle to mailchimp

### ISSUE THREAD

**Issue by slemo** [Myddleware/myddleware#306]
Hello myddleware, 
I have been having some issues transferring data from Moodle to Mailchimp. I have attached some screenshots below. There are a couple of errors I'd like to address:

- I have hundreds of users in Moodle, but the tool is only exporting 18
- The tool fails to insert into mailchimp and I can't tell what need to be done from the error provided.

![image](https://user-images.githubusercontent.com/9007606/81326947-3180b480-9060-11ea-8b58-54f93ddf6c02.png)

![image](https://user-images.githubusercontent.com/9007606/81327091-612fbc80-9060-11ea-8886-c26cfb8f7e3f.png)

![image](https://user-images.githubusercontent.com/9007606/81327142-6ee54200-9060-11ea-877a-97268426d36e.png)

**Comment by Myddleware** [comment]
HI @slemo ,

About your first point and the 18 records read. I guess that you didn't change the reference date in your rule. I see the first reference date in your record list is 2020-05-05 08:55:57. So you have probably created your rule the 05/05/2020 and Myddleware have read only the new users created or modified since the 05/05/2020. So you will just have to change your reference date to be able to read more users. Here is more info about it : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

But don't change your reference date yet, you have to fix the data transfer errors first. 

About the data transfer error, Myddleware displays the error returned by Mailchmp : https://mailchimp.com/developer/guides/error-glossary/
![image](https://user-images.githubusercontent.com/11330301/81390012-0a3aed80-911b-11ea-8ad1-e55cb512330b.png)

So we have to find which object generates the error. When I see your data transfer, your list id doesn't seems to be OK as it hasn't the right format. To get your list_id, please open Mailchimp, and click on Audience : 
![image](https://user-images.githubusercontent.com/11330301/81390726-3efb7480-911c-11ea-9f12-87db37dd00e9.png)

Then select your list and click on setting -> Audience name and defaults
![image](https://user-images.githubusercontent.com/11330301/81390841-694d3200-911c-11ea-8fcd-265b9363ea90.png)

Finally, you can retrieve the ID here : 
![image](https://user-images.githubusercontent.com/11330301/81390913-8aae1e00-911c-11ea-9467-19f1509ac1b0.png)

To try this, you can double click on the list_id (152619) in your data transfer, your field will be editable like this, change the list id, click on the Validation button : 
![image](https://user-images.githubusercontent.com/11330301/81391196-f7291d00-911c-11ea-9ca4-c9bb6ca4f522.png)

Then click on Reload the transfer : 
![image](https://user-images.githubusercontent.com/11330301/81391282-1cb62680-911d-11ea-9a62-4eaedd01394a.png)

If it doesn't work, we will have to found another solution. 
If it works, I advise you to cancel all your data transfer (you have to cancel them to be able to edit your rule), then edit your rule, change the list id in the rule. Then restart your rule. If data transfer are OK, you can set the rule reference date far in the past to be able to read all your users in Moodle.
 
For information, you can cancel several data transfer in the dat atransfer list view : 
![image](https://user-images.githubusercontent.com/11330301/81391724-de6d3700-911d-11ea-9253-e9f82499b6bc.png)

Please, let us know if it works.

**Comment by slemo** [comment]
Thank you. I was using the wing ID. I'm now having issues deleting the errored transfers. When I try to delete, it gives me an error. Is there a way to fish all the transfers and rules from the command line and start over?

**Comment by Myddleware** [comment]
Hi @slemo ,
Sorry but as it is another topic, it would be great to create another issue for that. Could you create one please ? And could you add in your post the command you send and the message you receive ? 
Thanks.
