### ISSUE TITLE
rule filter after first run

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#313]
I have create a rule without filter and run a sync
then I've been add a filter and run again rule
record that are excluded by the rule are still in CRM. I can delete manually, but then if these record match filter I suppose if deleted are no created again and get error? Or i can delete manually?
How to manage this situation?
Thanks!

**Comment by Myddleware** [comment]
Hi Simone,
You are right, if you delete manually a record in CRM and if the record match the filter in the future, because Myddleware has created the record in the past, It will generate an error. Myddleware will try to update a record which doesn't exist anymore.

Myddleware has to forget the ids of the records you have manually removed in CRM. So you can Cancel all your data transfer corresponding to these records. 

2 ways to do it : 

1. You can get all your document ids, using this query : 
`SELECT `id` FROM `document` WHERE `rule_id` = 'your_rule_id' and `source_id` IN ('target_id_1', 'target_id_2', '...'); `
The you can run the command : 
`php bin/console myddleware:massaction cancel document doc_id1,doc_id2,doc_id3.... Y --env=background`
Here more info about this command : https://myddleware.github.io/myddleware/#/api?id=apimass_action

2. The first solution is the good practice because it will log everything in Myddleware. But another solution is possible using a direct query like this one. It will be done faster but it is not really a good practice : 
`UPDATE `document` SET `status` = 'Cancel', `global_status` = 'Cancel' WHERE `rule_id` = 'your_rule_id' and `target_id` IN ('target_id_1', 'target_id_2', '...'); `
You can use target_id or source_id in the WHERE condition.

Please let me know if these solutions doesn't meet your needs.
