### ISSUE TITLE
Error Accessing Transfer / List

### ISSUE THREAD

**Issue by despindola** [Myddleware/myddleware#32]
Here is the error when opening the suggested URL: 
http://www.swiftparatodos.com/myddleware/web/app_dev.php/rule/flux/list/

An exception occurred while executing 'SELECT Document.*, users.username, Rule.name rule_name
FROM Document 
JOIN users ON(users.id = Document.created_by)
JOIN Rule ON(Rule.id = Document.rule_id)

WHERE created_by = 1
ORDER BY date_modified DESC 
LIMIT 1000':

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_by' in where clause is ambiguous
500 Internal Server Error - NonUniqueFieldNameException
2 linked Exceptions: PDOException » PDOException »

**Comment by Myddleware** [comment]
Hi Despindola,
There is a bug when you list the data transfer if your aren't an admin user. 

Line 334 of the file Myddleware\RegleBundle\Controller\FluxController.php : 
Could you change : 
$user = $cond.' created_by = '.$this->getUser()->getId();
By : 
$user = $cond.' Document.created_by = '.$this->getUser()->getId();

This bug will be fixed in Myddlewar 2.2.3. Could you let us know if your problem is solved.
Thanks.
