### ISSUE TITLE
How to manage when there is not a primary key in mssql

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#320]
Hi guys,
I'm managing a situation where table that customer give to use doesn't have a primary key. 
I'm importing addresses for customers. In this case result is that if I set as primary key customer code then I get only one address for customers. There is a way to avoid this situation, for example setting 2 fields to generate a "fake" primary key? (in my case "customer code" and "address number")

**Comment by Myddleware** [comment]
Hi Simone,
I see what you need. We have alreday done it for file connector. We will prepare a hotfix version for this, today or tomorrow. 
I 'll keep you posted.

**Comment by Myddleware** [comment]
Hi Simone,
Please update your Myddleware instance in version 2.5.4g and you will be able to select "Generated by Myddleware" in your rule : 
![image](https://user-images.githubusercontent.com/11330301/85571022-1d0a7280-b634-11ea-8510-83bdf288e1e3.png)

If you leave it like that, Myddleware will generate a new id for every record. It means that all your data transfer in this rule will create a new data in your target application. No update will be detected because all your ids will be differents.

But if you want to generate a custom id as you said with "customer code" and "address number". Then you can redefine in your custom class (<myddleware_root>\src\Myddleware\RegleBundle\Custom\Solutions\mysql.php if you use mysql or <myddleware_root>\src\Myddleware\RegleBundle\Custom\Solutions\microsoftsql.php if you use MSSQL) the method generateId() and add something like that : 
```
<?php

namespace Myddleware\RegleBundle\Solutions;

//Custom class
class mysql extends mysqlcore {
	
	protected function generateId($param,$record) {
		return $record['customer_code'].'_'.$record['address_number'];
	}
}
```
If you have several rules using the parameter "Generated by Myddleware", don't forget to filter your code with the rule_id using $param['rule']['id']

In this case, if the address is modified, Myddleware will read again the adress and generate the same id. So Myddleware will detect that this is an address modification.

Please let me know if I am not clear.

**Comment by simonetravaglini** [comment]
Great we will check and let you know!

**Comment by simonetravaglini** [comment]
Hi just used "generated by myddleware" and works. 
didn't checked custom function, but becouse related to mssql i suppose 
class mysql extends mysqlcore {
should be changed.

**Comment by Myddleware** [comment]
Yes, if you want to redefine the id and you use mssql, you shoudl create the file <myddleware_root>\src\Myddleware\RegleBundle\Custom\Solutions\microsoftsql.php and declare the class like this : 
`class microsoftsql extends microsoftsqlcore {`

**Comment by simonetravaglini** [comment]
Hi,
generated by myddleware works at first run, but if a second run is done record are duplicated if I set past date. So seems that didn't recognize record id generated by myddleware.

**Comment by Myddleware** [comment]
Hi Simone,
Maybe, I wasn't clear when I explained that just above here : https://github.com/Myddleware/myddleware/issues/320#issuecomment-648845864

If you don't redefine the method generateId, a new Id will be generated for every data transfer. If you want to generate you own id (and detect an update) you have to redefine the method generateId. An update will be detected only when an id already exists in Myddleware for the same rule. So if your create an id like this $record['customer_code'].'_'.$record['address_number'], Myddleware will detect the update and won't create duplicate data.

Please let me know if I am clear. Thanks.

**Comment by simonetravaglini** [comment]
not clear. In this case I don't need to generate my own id. So my expectation is that in first run an id is generated by myddleware and in second run record is updated. It's not correct?

**Comment by simonetravaglini** [comment]
I've been read again your comment, if I correctly understand it's necessary (and also logic :) ) set fields to create the id if I want manage updates.

**Comment by Myddleware** [comment]
Yes @simonetravaglini 
Please let me know if you have other issues on this topic.
Thanks.

**Comment by simonetravaglini** [comment]
Hi guys, we succesfully used this function! Thanks for support! :)

**Comment by Myddleware** [comment]
Good news. Thanks for your feedback.
