### ISSUE TITLE
mapping

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#338]
Hi,
when try to map relation I faced an issue.
Seems that in source fields retrieved are only fields with ID in name. Is it possible? How does it works?
We tested on myssql connector.
![image](https://user-images.githubusercontent.com/6990139/89537877-33dae200-d7fa-11ea-90d2-119a99d88fb6.png)

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Yes, because we don't know the fieldname in advance, we have to set a rule to detect relationship field. A fiels is in the relate list if its name starts or finishes by "id" or "ID".
But you can redefine the method getIdFields (don't modify the standard one if you want to keep your Myddleware "upgrade safe"). We have created this method in case you need to add a specific relate field.
Please let me know if you need any help to redefine this function.
