### ISSUE TITLE
How to integrate with Suitecrm ? 

### ISSUE THREAD

**Issue by Inv0k-er** [Myddleware/myddleware#344]
Hello I have a Moddle and I wana integrate with Suitecrm use Myddleware.
But I can't found guide. How to do it ?  How to Integrate Moodle and SuiteCrm ? 
I have a Errors:
Error1
![myddleware-error1](https://user-images.githubusercontent.com/42607075/90008258-de9d4580-dcbd-11ea-914d-16048cf41ee4.PNG)
Error2
![myddleware-error2](https://user-images.githubusercontent.com/42607075/90008266-e2c96300-dcbd-11ea-832d-ffccb558ed42.PNG)

My config:

![my-config](https://user-images.githubusercontent.com/42607075/90008353-0096c800-dcbe-11ea-8c3f-6d77bf7f5c60.PNG)

My connectors:
![connectors](https://user-images.githubusercontent.com/42607075/90008419-1a380f80-dcbe-11ea-9e03-4704316d0ff2.PNG)

Suitecrm
![suitecrm](https://user-images.githubusercontent.com/42607075/90008465-3340c080-dcbe-11ea-9e0b-463ec70b7379.PNG)

**Comment by Myddleware** [comment]
Did you try to put your rule reference date in the past ? The reference date is set by default to the rule creation date. If no Moodle records (users, courses... depending on the module you want to read) has been modified since this date, then Myddleware has nothing to read.

You will find more info about the reference date here : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters
Please, let me know if it has solved your issue.

**Comment by Inv0k-er** [comment]
ok I give you answer in next week. I wana read your link.
