### ISSUE TITLE
ENTITY IS DELETED

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#357]
Integration between Moodle & Salesforce 

whenever an entity gets deleted in either of the system, we get an error saying "ENTITY IS DELETED" . How to overcome this issue ?  we would need the record to be deleted at the other system as well or it should allow us to recreate .

**Comment by Myddleware** [comment]
OK, for exemple, if you delete manually a record (createb by Myddleware) into Salesforce, and if you modify the corresponding record into Moodle, then Myddleware will read this record from Moodle and try to update it into Salesforce. An error will occur because Myddleware will try to update a record that doesn't exist anymore. It hapends because Myddleware don't know that you have deleted the record in Salesforce.

In this case, the good practice is to always delete the corresponding record into Moodle when you delete a record into Salesforce and vice versa. 

Another way is to force Myddleware to forget the record by cancelling or removing all the data transfer corresponding to this record in Myddleware. The only way to do that is to use this command : 
`php bin/console myddleware:massaction <remove/cancel> document <your data transfer ids> Y --env=background `
The documentation for this command is here : https://myddleware.github.io/myddleware/#/api?id=apimass_action

Another way is to develop a custom code in Myddleware which force Salesforce to create the record again when the error "ENTITY IS DELETED" is returned by SalesForce.

Finally, Myddleware can delete records but only with SuiteCRM and database (MySQL, MSSQL) connectors for the moment. To enable this feature for other application, Myddleware needs to know which record has been deleted. Only a few applications have a webservice function that can do this. This isn't the case with Moodle.
