### ISSUE TITLE
Connection between Moodle and SuiteCRM not working

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#360]
HiAdmin,

I have configured both SuiteCRM and Moodle in Myddleware. Link is ok. However when I try to map the fields and test rue it always shows "There is no data in the source server or fields in the target solution".

I have imported "Myddleware user" in moodle as per the guide. Gave the user Sysadmin rights. 
If I try passing Jason in browser every other function works except "core_user_get_users". This gives me below error :
{"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected","debuginfo":"Missing required key in single structure: criteria"}.
Rest all functions are returning the data. 
I have attached the screenshots. 

Kindly help here.

Regards
Himanshu
[My rule in Myddleware.docx](https://github.com/Myddleware/myddleware/files/5321432/My.rule.in.Myddleware.docx)

**Comment by Myddleware** [comment]
Hi @himanshunandan ,
Could you send me a private message using our contact page on our website : http://www.myddleware.com/contact-us
I will give you the access to a Moodle test instance to check if the problem comes from your Moodle instance?

**Comment by Myddleware** [comment]
Oh I think about something. For performance purpose, during the simulation, Myddleware don't read data oldest than 1 year. Maybe you don't have recent data in your Moodle instance. In this case, you can change the attribut delaySearch in the Moodle class (<myddleware_root>\src\Myddleware\RegleBundle\Solutions\moodle.php)
![image](https://user-images.githubusercontent.com/11330301/95111238-7f006b00-073f-11eb-8402-1953b9b767e1.png)

You can put "-5 year" instead of "-1 year" for example.

**Comment by himanshunandan** [comment]
Thanks for your help. I have moved to erpnext and trying myddleware there.
