### ISSUE TITLE
Number of record processed it's not coherent

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#376]
Hi guys
look here:
![Clipboard - 30 ottobre 2020 09_18](https://user-images.githubusercontent.com/6990139/97689125-6dd71f80-1a9b-11eb-8577-b84d85a031d1.png)
Then rules is run, but:
![Clipboard - 30 ottobre 2020 10_24](https://user-images.githubusercontent.com/6990139/97689156-792a4b00-1a9b-11eb-87e1-411e8ede76a5.png)

In rule there is a filter, so it's normal that record are skipped, but total record processed it's not coherent with first image.
Do you have an idea what we can check?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Yes, the numbers sould be the same i both screenshot. 
Could you tell me what is the source application connected to this rule (for example MySQL ) ? 

It could happen if the id selected in your rule isn't unique. In this case Myddleware will merge the records because the record ID is the key of the result array of the read function.

**Comment by simonetravaglini** [comment]
Hi @Myddleware ,
I confirm that we are working on MSSQL And ID selcted is unique.
Any ideas what we can check?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I guess that you have 20 735 records (not 5 715 : 5456 + 259) in your database, isn't it ? 
We need to reproduce this issue. Is there a way that you send me privately a dump of your table ? You could remove sensible data, I just need the ID field and the reference field.
Thanks.
