### ISSUE TITLE
regarding prestashop to erpnext

### ISSUE THREAD

**Issue by Samirius** [Myddleware/myddleware#389]
tried to create a rule between PrestaShop to Erpnext or vise versa but I can find no option to select in modules selection of PrestaShop side

https://prnt.sc/vx0rfi

can you please help me?

**Comment by stlgaits** [comment]
Hello,

I think you may not be properly logged in to Prestashop, either that or your token doesn't have sufficient authorizations. Could you check that you have granted the permissions you need on your token like in the example below ? You do not need to check all the modules in there, just the ones you need to access : 
![permissions](https://user-images.githubusercontent.com/74190794/101460247-a2ab8180-3939-11eb-9333-8a22eb7def9b.png)

Could you double check that your connection to the Prestashop webservice is active ? If you're not sure on how to do this, have a look at this previous issue I think it might help too : 
 https://github.com/Myddleware/myddleware/issues/299#issuecomment-656659956

**Comment by Samirius** [comment]
thanks for the tips, after removing the old API and making a new connection, I have found the connection successful and could create a rule (I mean to have the ability to create one)

but now I have no idea what to choose and how to create the rule regarding the orders sync or quantities (stock management)

as the whole idea is creating a sync between woocommerce stock and prestashop stock, updating 1 affects the other

and ERPNext is in the middle.

would appreciate any guidance

**Comment by stlgaits** [comment]
Good news ! 
 
I just a have few questions to understand your situation better and try to sort this out for you : 

- Are your products already on ERPNext or are they going to be created by Prestashop via Myddleware?

- What module do you use for your  products in ERPNext ? 

Based on what you wrote, so far I would recommend the following : 

- creating a rule from Prestashop to ERPNext in which you send 'available quantities' from Prestashop to the module you've used in ERPNext for stock

- creating a rule from Prestashop to ERPNext for 'products' (otherwise you won't be able to send quantities)

Also, you will have to be extra careful with how you handle the bidirectional synchronisation, taking into account a situation where for example stocks are modified by both Prestashop and Woocommerce at the same time. 

Keep me posted !

**Comment by Samirius** [comment]
Thanks :)

Are your products already on ERPNext or are they going to be created by Prestashop via Myddleware?
no, not yet. 

What module do you use for your products in ERPNext ?
i don't, but it is connected to my woocommerce test site with their official module/plugin (using hooks it is not a 3rd party one)

about creating rules, I don't know which to choose precisely to do what you have mentioned like for orders/products there are more than 1 thing to pick.

so which are the ones to choose in my rules, and how many rules I need?

another question is, can I use myddleware for migrating/copying my products form prestashop to woocommerce?

if yes, how would that be possible using myddleware and erpnext in the middle while my products have attributes/variations like size, color, etc?

i see a good almost great potential for myddleware and would like to help in development if I can (but my experience limits are in project management, UX/UI, and marketing) please if you need any help in this let me know i would like to contribute.

**Comment by Myddleware** [comment]
Hi @Samirius ,
I think you will need at least 6 rules to connect Prestashop and ERPNext : 
 - Sending Customers (The e-shop customers) from Prestashop to ERPNext
 - Optionaly : Sending Customers addresses (The Customer, Brand and Customer addresses) from Prestashop to ERPNext
 - Sending Orders (The Customers orders) from Prestashop to ERPNext
 - Sending Order lines (Details of an order) from Prestashop to ERPNext
 - Sending products (The products) from Prestashop to ERPNext
 - Sending products variation (The product combinations) from Prestashop to ERPNext
 - Sending stocks (Available quantities) from Prestashop to ERPNext

You have also a third software Woocommerce. We have released Woocommerce connector this Monday! So we haven't communicated about it on our websites yet, but Myddleware can read date from Woocommerce (no data creation yet).

As you know, the interface you want to build isn't an easy one. We definitely can help you but this forum isn't the good place. Forum is good to fix issues or answer quick question, but in your case you need to build a whole interface between 3 applications. 

If you want to discuss with us about the service we can offer, please contact us directly via our contact page http://www.myddleware.com/contact-us

Otherwise you can try to build your interface and we will be there to help you if you have an issue or a specific question.

Hope the rule list will help you.
have a nice day.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
