### ISSUE TITLE
How synchronize from source table without a proper `date_ref` field?

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#398]
## Description

In this discussion  https://github.com/Myddleware/myddleware/issues/293  the proposed solution has a drawback

The idea is override the `date_def` value at every sync loop, in this way all record in the source are ever NEW (good move!)

```php
class mysql extends mysqlcore {
	public function read($param) {
		if ($param['rule']['id'] == 'you_rule_id') {                        
			$param['date_ref'] = '2000-01-01 00:00:00'; /* The override line */
		}	
		return parent::read($param);
	}
}
```

The override line replace `date_ref` on the follow 

![Workspace 1_023](https://user-images.githubusercontent.com/472171/104340258-c9407780-54f8-11eb-90a6-811313aa7684.png)

But is important take note by what field you use instead of your missing `date_ref` field.
Someone generally use the Primary key field, as follow

![Workspace 1_024](https://user-images.githubusercontent.com/472171/104340818-5edc0700-54f9-11eb-9e40-2daf937e9c47.png)

BUT 

## The problem

this create a bad READ query with CASTING and DATETIME conversion (uncontrolled conversion)

```sql
  SELECT [Tipologia], [IDTipologia] 
    FROM [TAB_Tipi_Voci] 
   WHERE [IDTipologia] > '2000-01-01 00:00:00' 
ORDER BY [IDTipologia] ASC 
```

The condition in the `WHERE` section is out of our control and can get unexpected results, in fact we can have this

| IDTipologia | [IDTipologia] > '2000-01-01 00:00:00'  |
| --- | --- |
| 1 | FALSE
| 1000 | TRUE |
| AS100 | TRUE |
| 0K10 | FALSE |

Because the SQL interpreter not compare DATETIME vs DATETIME but INTEGER or VARCHAR on the left side.
This query select not all record, but just the one are lucky on the DATETIME conversion

## Strategy

We looking for Syncronize all RECORD from the source in a smart way, a good plan is to use an unique key as `date_ref` field
to split large source into sync slot. In other words supporting 'date_ref' field or any sortable and comparable unique key field (eg. primary key or custom key) depending on the choise for REFERENCE field (Integer, Varchar, Datetime, etc...)

**Comment by Myddleware** [comment]
Hi @francescobianco ,
This custom code we have provided to you seems to generate several bugs. We thought your reference field type would always be a date. 
When we developped Myddleware, we have named this field reference_date which is wrong because, now, Myddleware can work with a reference field that isn't a date. 
In your case, I would advise to change the default value for this field depending of the type of the reference filed in your rule. For example, if you have a rule with an integer as reference field type , and another rule wth a date as reference field type, the custom code should be like this : 

```
class mysql extends mysqlcore {
	public function read($param) {
		if ($param['rule']['id'] == 'you_rule_id_1') {                        
			$param['date_ref'] = '2000-01-01 00:00:00'; /* The override line */
		} elseif ($param['rule']['id'] == 'you_rule_id_2') {                        
			$param['date_ref'] = '0'; /* The override line */
		}	
		return parent::read($param);
	}
}
```

If the reference type of your rule is a string, maybe you could test with default reference field = '' . But we never used a rule with a string as a reference field type. We just know that it works properly with types : integer and date. 
Please, keep us updated.

**Comment by francescobianco** [comment]
Hi @simonetravaglini please follow this

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
