### ISSUE TITLE
what does it mean "retrieving existing data only"?

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#402]
if I select this option what will happen? IT will update only data already present in target?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Myddleware will just search the data in the target application and create a correspondance between the id of the source and the id of the target application. Myddleware will never create or update data for this rule. It can be use when you need a reference without changing target data for a specific data. 

For example, you want to create contacts and link them to your account in the target application, and the accounts already exist in the target application. But you don't want to change the account in the target appliaction. In this case, you will create a rule for account by selecting "Retrieve existing data only". You have to select a duplicate field in parameters tab too, like email field for example. Otherwise Myddleware will have no way to search the account.
Then you can create the second rule for contact using the account rule to link your conrtact to the right account into the target application.

Hope it is clear.
