### ISSUE TITLE
data exchange between erpNext and prestashop ->Error : Failed to find the language in the Prestashop XML 

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#421]
Dear myddleware community,

I've installed erpNext and prestashop. Now I want to transfer item data from erpNext to prestashop. The transferprozess stopped with the error message "Error : Failed to find the language in the Prestashop XML /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/prestashop.php Line : ( 958 )Failed to send document. Status : Error_sending".
I' would be happy if you could help me with an approach of solution.

best regards
Andreas

**Comment by Myddleware** [comment]
Hi Andreas,
Could you tell us which data (module) you are sending to Prestashop ? And we will try to reproduce your issue.
Best regards

**Comment by userGitHub75334** [comment]
Thanks a lot for your fast response.
I use with the erpNext connector the modul "Item" and with the prestashop connector the modul "The products". 
best regards 
Andreas

**Comment by Myddleware** [comment]
Thanks @userGitHub75334 
We could reproduce the issue and we have fixed the bug. In your case the language wasn't displayed in your rule.  You could apply manually this fix : https://github.com/Myddleware/myddleware/commit/291d78a8f57074b436fa7fca8f6327e030d8a097
Then you will see the language here : 
![image](https://user-images.githubusercontent.com/11330301/106790339-b5011d80-6653-11eb-8b0c-58b1fb2ced89.png)

Otherwise, you can wait for the new Myddleware version (tomorrow), version 2.5.7. In this case, you will just have to upgrade Myddleware as we have added this fix to this new version.

**Comment by userGitHub75334** [comment]
Thank you for your quick response and the solutions.
I will give you feedback on my results.
First I tried your suggestion with the update. But I already installed version 5.1.7 on Monday February 1st, 2021 and I think that's why I didn't get your modified prestashop.php this way.

Then I tried your manual fix 291d78a and it worked. I'm one step further now.

Thank you for your help
Best regard
Andreas
