### ISSUE TITLE
Manage big DB: best practice for first run

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#422]
Hi guys,
we are syncing a Db to vtiger.
We are working on company, 50k records.
I launched rule yesterday and it's still running (29k done in status new). 
Seems that our problem is that for this first run we have all data with same data ref, so we have to set 50k for every run.
There is a way to better manage this situation and have a faster sync? I don't have idea how long will work to complete this task :(

**Comment by Myddleware** [comment]
Hi @simonetravaglini,
Myddleware performance decreases after 2k records, so it will take a very long time for 50k records... and Maybe your server won't be able to finish it. You should configure a limite to 1k records. However, if all your records have the same data ref, you can't set a 1k record limit because Myddkeware won't be able to restart after the latest record read. Somigration won't work.

For information, the next main Myddleware version based on Symfony 4.4 will be compatible with php8. Perfermance will definitely be improved. We plan to launch this version in March.

About your problem, we already had this situation in the past. Here is what we have done : 
 - Create a new field (temporary field) in your database like. In the example, we will name it "date_ref2"
 - Update this field with a random value base on your first date ref field. With this query, your "date_ref2" field will be almost equal to date ref  (date ref = "date_ref2" minus between 0 and 1000 seconds) : UPDATE <table> SET <field date ref 2> = DATE_ADD(<field date ref>, INTERVAL (FLOOR(RAND() * (-1000))) SECOND)
 - Save the current date (when you execute this query)
 - Then change the ref date field of your rule using the ref date field 2 and run your rule with 1k limit until all ata is sent
 - When it is finished, change again the ref date of your rule with your first ref date field 
 - Set the reference date to the date you have saved before updating the ref date field 2 in your database. This step is important to avoid to miss the new data created after you have update the field "date_ref2"
 - Your data are migrated, now Myddleware can work normaly with the first date ref. You can remove the date ref2 from your table 

Please let me know if it helps.

**Comment by simonetravaglini** [comment]
thanks for tips we solved! :)
