### ISSUE TITLE
Create commands to create a user, add and remove a role

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#431]
We need to create the commands to create a user, add and remove a role

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/109659810-61a5c080-7b68-11eb-9dc1-48dff2209eb2.png)
The command currently works, the user is created in the database, however it is not yet possible to login with the user created. I believe this is due to the fact that the salt column is left on null (could be to do with FOSUserBundle ??). 
Also for now the user only has ROLE_USER if you use the interactive wizard. Do we want to have all users with ROLE_ADMIN as a default or do I need to ask a question on the wizard asking whether you want to promote the user to admin / leave it on ROLE_USER  ?

**Comment by stlgaits** [comment]
For now, all created users are admin by default

**Comment by stlgaits** [comment]
Added command to promote a user. 
![image](https://user-images.githubusercontent.com/74190794/110507475-58849880-8100-11eb-9556-df44ffce7160.png)
![image](https://user-images.githubusercontent.com/74190794/110507547-6803e180-8100-11eb-9b92-9b54db81cad8.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/110616382-c4184580-8194-11eb-9213-79337d1fd816.png)
![image](https://user-images.githubusercontent.com/74190794/110616529-edd16c80-8194-11eb-86cd-2a9dca50b4da.png)
