### ISSUE TITLE
Moodle integration Create Category

### ISSUE THREAD

**Issue by subhankar** [Myddleware/myddleware#432]
Hi 
After creating a new connection, I can not see Moodle Category option in the modules pull down. Can we push Course Category also in Moodle from SuiteCRM? Does it require any other functions to add in Myddleware service. 

![Untitled2](https://user-images.githubusercontent.com/608589/107654163-659c9c00-6ca8-11eb-9c36-747ebb1e5d04.png)

**Comment by Myddleware** [comment]
Hi @subhankar,
You are right, catagories aren't managed yet in the Moodle connector. 
If you are developer we could guide you to develop it, and in retrun you could share your code as contributor on our open source project. 
Otherwise, we can develop it for you. In this case, contact us directly via our contact page http://www.myddleware.com/contact-us
Have a nice day.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be. 
Thanks
