### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#449]
This search failed : 
![image](https://user-images.githubusercontent.com/11330301/108250526-a6882b00-7156-11eb-979f-725bb6cd214a.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/109994349-84250e80-7d0d-11eb-8a37-b4191c69b7ae.png)
In DocumentRepository.php line 313
removed `&& $data['page'] != 1 `from condition as it was the cause of the problem, now it nearly works but there are issues due to pagination still as this error is thrown from FluxController.php line 807  : 
`     } catch (\Pagerfanta\Exception\NotValidCurrentPageException $e) {
                    //Si jamais la page n’existe pas on léve une 404
                    throw $this->createNotFoundException("Cette page n'existe pas.");
                }
`

**Comment by Myddleware** [comment]
Search is fixed : 
![image](https://user-images.githubusercontent.com/11330301/110049014-434ee900-7d51-11eb-92a1-0b7242f9ec75.png)
