### ISSUE TITLE
Fields to avoid duplicates not persists

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#456]
If Edit existing rules the fields to avoid duplicates, start as resetted not are showed as I saved it

![Screenshot from 2021-02-26 11-06-05](https://user-images.githubusercontent.com/472171/109286653-d3a59f00-7822-11eb-8169-5d3fd1b9fa1e.png)

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Which Myddleware version are your using ? Because we have fixed this bug few weeks ago in version 2.5.6 (https://github.com/Myddleware/myddleware/commit/3df255a3b7ef1b465febd57dad976245bc7532f4) : 
![image](https://user-images.githubusercontent.com/11330301/109290006-57fa2100-7827-11eb-8930-b038451c4498.png)


If you have the latest version then could you tell us which module and which application are your using in your rule ? 
Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
