### ISSUE TITLE
Delete transfers button

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#457]
Hi! I became aware of the presence of two buttons (as in the image)
![unnamed](https://user-images.githubusercontent.com/472171/109618362-bda42100-7b37-11eb-8373-5b015faae86d.jpg)
But I never see it in the code. Please could you point me to the code of this button, or suggest some trick to get in on my instance.

Thanks always for your kindness

@simonetravaglini

**Comment by stlgaits** [comment]
Hello @francescobianco, these buttons are available since Release 2.5.7. To be able to see  these buttons you need to promote your user to ROLE_SUPER_ADMIN as you can see in the twig code below. 
To promote your user, use the following command in your terminal : 

php bin/console fos:user:promote <myddleware_username> ROLE_SUPER_ADMIN -e prod 

In case you want to see the code to display them it is located in src/Myddleware/RegleBundle/Resources/views/Rule/edit/onglets/infos.html.twig  lines 61 to 72: 

![image](https://user-images.githubusercontent.com/74190794/109621649-89cafa80-7b3b-11eb-9164-80ff30798fda.png)


Hope this helps,

Estelle

**Comment by francescobianco** [comment]
Hi, @EstelleMyddleware many of my instances miss the ROLE_SUPER_ADMIN as the default flag for the ADMIN user,
How I can add it to existing users, in a way to have these two buttons?
I noticed that the code upgrade alone is not enough I think the database needs something.

**Comment by francescobianco** [comment]
Thank you very much, it is really very useful, I will immediately use it
