### ISSUE TITLE
Button to generate template not displayed

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#466]
A button should be displayed gere to generate the template : 
![image](https://user-images.githubusercontent.com/11330301/110533830-af00cf80-811e-11eb-90cd-88f02bf5e2df.png)

**Comment by stlgaits** [comment]
The origin of the problem is linked to PrestaShopWebService.php file.

The following error is triggered, hence stopping execution and therefore the button doesn't appear : 
`Bad HTTP response  ..\myddleware\src\Solutions\lib\PrestaShopWebservice.php line 144`

![image](https://user-images.githubusercontent.com/74190794/110607088-25d3b200-818b-11eb-840b-9fb3cf55a870.png)

which also throws the error : 
`Notice: Array to string conversion   ..\myddleware\src\Solutions\prestashop.php  line 186`

then in TemplateManager.php : 
```
Warning: array_intersect_key(): Expected parameter 2 to be an array, null given  
..\myddleware\src\Solutions\prestashop.php  line 205

```
then in DefaultController.php line 2588 : 
`There is no active transaction.   \myddleware\vendor\doctrine\dbal\lib\Doctrine\DBAL\ConnectionException.php line 23`

Which in turn is sent to animation.js  line 544. Because the data received is 'There is no active transaction', the button remains stuck on 'Please wait...' indefinetely.

**Comment by stlgaits** [comment]
I've added jobManager->orderRules() however I am not sure why  I get a circular reference error 

![image](https://user-images.githubusercontent.com/74190794/110663455-bd0a2b00-81c6-11eb-8a58-b5f4fe88533a.png)

**Comment by Myddleware** [comment]
Circular bug fixed and button is displayed

**Comment by stlgaits** [comment]
The problem linked to Prestashop seems to not be fixed yet.
When running all rules from the tutorial (Prestashop to SuiteCRM) I get the following error  
![image](https://user-images.githubusercontent.com/74190794/111296061-582e5500-864c-11eb-8acc-8098be32aa51.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/111644772-6d4be500-8800-11eb-91da-423f639c4685.png)
closing this issue as the button works fully and opening issue regarding prestashopwebservice.php
