### ISSUE TITLE
How to add an update field criteria to a connector

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#501]
I'm using myddleware to copy records from Facebook to Vtiger. 

At the last step of the Rule creation I get the following:

![image](https://user-images.githubusercontent.com/36896420/114629965-2b875080-9c7f-11eb-8b74-f3567ca16455.png)

I'd like to add a new field as duplicate criteria. Above there is email and lastname. I'd like to add phone. How can I do that?

I'd also like to ask how does the update feature work? Does it overwrite existing fields when they have a value? Or does it only update fields that are currently empty?

**Comment by stlgaits** [comment]
Regarding the update feature first, the way it works is it overwrites fields that have been modified since the reference date, therefore it doesn't really 'matter' whether the field was empty or not as it will be overwritten if there is a change.
As for adding 'phone' to your duplicate criteria, you would need to add a bit of custom code for your target connector (so if it's Vtiger for instance, you will need to go to 

> src/Myddleware/RegleBundle/Custom/Solutions/vtigercrm.php  

(if the 'Custom' directory doesn't exist, simply create it)
and add the field 'phone' for the module you have selected in this array  : 
![image](https://user-images.githubusercontent.com/74190794/114671887-ddb52b80-9d04-11eb-9d76-f96dcc05bdab.png)
So you should have the following code in the end (of course you can customise it in whatever way you want) : 
```
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class vtigercrm extends vtigercrmcore {

	protected $FieldsDuplicate = array(
								'Contacts' => array('email', 'lastname', 'phone'),
	                                                        'CompanyDetails' => array('organizationname'),
	                                                        'Accounts' => array('accountname'),
								'Leads' => array('email',' lastname'),
								'default' => array('')
							  );
		
}

```

Here is a similar example of the same process but with SalesForce instead of Vtiger. https://github.com/Myddleware/myddleware/issues/351#issuecomment-696207474

Hope this helps.

**Comment by rulotec** [comment]
Thanks Estelle, it worked perfectly!
