### ISSUE TITLE
Can't create a rule with the same name as one that existed but is deleted

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#504]
I cant create a rule with the name "Multivitamin Abril":

![image](https://user-images.githubusercontent.com/36896420/114796921-ac198000-9d57-11eb-9b03-83d8e97c920e.png)

In my rules I have the following:

![image](https://user-images.githubusercontent.com/36896420/114796994-cce1d580-9d57-11eb-9eef-0ba10e0694c7.png)

"Multivitamin Abril" used to exist but was deleted.

I'm not sure whether this is a bug or it is intentional.

**Comment by stlgaits** [comment]
Hi, simply remove one or two characters and type it again and you will be able to save it.

**Comment by rulotec** [comment]
Thanks Estelle. Yes, that is exactly what I did (see the rules list in my previous comment). However I reported it because to me it seems to be a bug. Unless (for some reason) that behavior is intentional.

**Comment by Myddleware** [comment]
Hi @rulotec ,
Myddleware doesn't remove completely the rule but only set the flag deleted = 1 in the database because it is possible to restore a rule. And, in Myddleware, it isn't possible to have 2 rules wth the same name. It is the reason why you can't set the same name to 2 rules, even if one of them is removed.
However, if it is important for you to set the same name, you can change the name and name_slug field of the old rule in the database (table rule), then you will be able to set the name you want to the new rule.
Hope it helps.

**Comment by rulotec** [comment]
But the end user can't restore the rule, can he? To restore a rule I would have to edit mentioned flag in the DB, right?

**Comment by Myddleware** [comment]
Yes for the rule, you have to set 0 into the table Rule for the rule you want to restore. 
For the data transfer, there is a command (massaction) to restore all data transfer .
