### ISSUE TITLE
Can't delete rule because there is "at least one data transfer not deleted on this rule", but all are canceled or sent

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#505]
Im getting this error:

> Failed to delete the rule because there is at least one data transfer not deleted on this rule. Remove these transfers to be able to delete this rule.

![image](https://user-images.githubusercontent.com/36896420/114797242-5abdc080-9d58-11eb-8b80-ffd897a0f828.png)

However all my transfers are in status "Send" or "Cancel":

![image](https://user-images.githubusercontent.com/36896420/114797327-89d43200-9d58-11eb-9880-703036591dbf.png)

I tried to find a way to "remove" the transfers as the error suggests but it doesn't seem to be possible.

**Comment by stlgaits** [comment]
Hello, you need to have the role super admin to be able to remove transfers in error.
Here is the procedure to do so : 
Go to your myddleware root folder and type the following command (replace myddleware_username by your actual username) : 
`php bin/console fos:user:promote myddleware_username ROLE_SUPER_ADMIN -e prod`
Then go back to your rule's information tab and click on the button delete transfers : 
![image](https://user-images.githubusercontent.com/74190794/114876602-c5293c00-9dfe-11eb-90e9-a6daabc3e583.png)
Here is a topic on the same issue : 
https://github.com/Myddleware/myddleware/issues/457
⚠️  Please be aware that once you will have removed these transfers, Myddleware will not be able to know whether the data in your system has already be read or not (since the transfers have been deleted), so ensure you check your transfers first (to avoid duplicate records for instance). ⚠️

**Comment by rulotec** [comment]
Thanks for the tip! One question, is it safe to delete a rule when all transfers are in either "cancel" or "send" state? If so, why not let the user delete the rule without having to delete the transfers?

**Comment by Myddleware** [comment]
Hi @rulotec ,
It isn't possible to remove a rule if there are data transfers linked to it (foreign key restriction in the database). So all the data transfers have to be removed before the rule is removed. 
By the way, it is just a soft deletion (flag deleted = 1) in the database. So it is possible to restore a rule or data transfers.

**Comment by rulotec** [comment]
If it's just a soft deletion, then the foreign key restriction doesn't matter, right?

IMHO, I think you should either give the ability to delete transfers that are in status cancel or send, or be able to delete the rule when all transfers are in status cancel or send.

**Comment by Myddleware** [comment]
Yes you are right, I didn't want to explain everything. But yes, the foreign key was just to explain that we can't "hard"remove the rule if the data transfer aren't "hard deleted" too.
But please let us know what you need an we will try to help. We don't plan to change the "deletion" process for now but maybe we can help to fin a workaround.

**Comment by rulotec** [comment]
Ok, I get it.

What I wanted was 2 things:
1. Understand how I could delete rules. Which is now clear: get a super admin, delete the transfers and then the rule.
2. Try to give ideas and feedback to improve myddleware.

I'm happy with the first one. As for the second one, I hope you are happy too.

**Comment by Myddleware** [comment]
@rulotec ,
Yes we are very happy with the second one. Thanks for helping us to improve Myddleware. Today we are focusing on the Myddleware's framework upgrade to Symfony4, it is a very big step. Then we will focus on a new web interface, because this one becomes old ;). 
Don't hesitate to send other feedback.
Have a nice day.

**Comment by rulotec** [comment]
Sounds great! Thanks for the support :)
