### ISSUE TITLE
Template rules aren't generated 

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#528]
When we try to generate a template, the rule aren't créated : 
![image](https://user-images.githubusercontent.com/11330301/117172794-6d15a200-adcc-11eb-835a-e9166f103748.png)

**Comment by stlgaits** [comment]
This problem seems to be linked to Prestashop as it only occurs on this template, I was able to generate a Woocommerce to Vtiger template without any issues, however when trying to reproduce your case from Prestashop to SuiteCRM, I get the following error on validation request : 
![image](https://user-images.githubusercontent.com/74190794/117789805-00295e80-b249-11eb-9f4f-94c0bae5da47.png)

**Comment by stlgaits** [comment]
https://github.com/Myddleware/myddleware/issues/482
https://github.com/Myddleware/myddleware/issues/466

**Comment by stlgaits** [comment]
The problem seems to be linked to our 1.7.7 Prestashop version as I was able to generate template with Prestashop 1.7.0
![image](https://user-images.githubusercontent.com/74190794/117975196-b5821200-b32e-11eb-9cc4-e5b41e09e870.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware , I confirm that this issue is linked to Prestashop 1.7.7. I will check if it happens becuse of our test environment or if it is linked to this Prestashop version.

**Comment by Myddleware** [comment]
@EstelleMyddleware , good news, it isn't a bug. Prestashop 1.7.7 wasn't working properly because our test server was in php version 7.4 and Prestashop 1.7.7 is compatible PHP 7.1, 7.2 and 7.3, not 7.4. I have changed the php version and I could generate the template with Prestashop 1.7.7.
