### ISSUE TITLE
space missing

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#533]
Hi,
I'm importing a value from mssql, in DB value is
`C  2950` (2 spaces between letter and numbers)
but after import become
`C 2950` (1 space)
do you have an idea?
@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini,
Could you give me more detail about the rule and this field? The field that contains C  2950, is it an "ID" or does it contain a formula ?  
We will try to reproduce it and the fixe it.
Thanks.

**Comment by simonetravaglini** [comment]
@Myddleware 
Hi, we don't have any formula related to this field, the field have not a function of "ID" but contain ID in the name.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I have tried to reproduce the issue and I found that the bug is only a display bug in Myddleware user interface here (only 1 space) :  
![image](https://user-images.githubusercontent.com/11330301/118696928-128a3600-b80f-11eb-92a8-9f563732d7ee.png)

But the 2 spaces are correctly sent to the target application. Here are the date in Myddleware database (target and source documents have 2 spaces) : 
![image](https://user-images.githubusercontent.com/11330301/118697287-6dbc2880-b80f-11eb-97d8-430314ec6766.png)

Here is the data sent with 2 spaces too : 
![image](https://user-images.githubusercontent.com/11330301/118696537-ad364500-b80e-11eb-916e-57a46f03c27f.png)

Could you confirm that this issue in just a display bug and not a issue in the data read and sent ? Thanks.

**Comment by simonetravaglini** [comment]
@Myddleware in my case it's not a display error, but vtiger record field is wrong.

**Comment by Myddleware** [comment]
@simonetravaglini , 
OK, could you give us the detail of your rule and your data transfer (with screenshot if possible). We will need it to try to reproduce this issue. 
Thanks.

**Comment by simonetravaglini** [comment]
Hi seems that I was wrong, finally the data transfered it's ok. I do some other tests and let you know.
