### ISSUE TITLE
Magento 2 to ERPnext Simulated transfers

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#550]
Simulated transfers show 0 when simulating the transfers and rule does 0 transfers any way around this or a fix?

I'm trying to transfer 20k +/- products from magento 2 to ERPnext i have set the date to before the first product was created but myddleware cant see it somehow?

![image](https://user-images.githubusercontent.com/21164341/126249134-f771d12e-ee84-4e78-9016-08c7cd3c6145.png)

**Comment by ModeBan** [comment]
seems like the request is getting timed out

**Comment by Myddleware** [comment]
Hi @ModeBan ,
We are working on Magento connector to make it compatible with Magento 2.4.
We 'll keep you posted.

**Comment by ModeBan** [comment]
@Myddleware all the connectors work fine you can see the data the only thing I can't get working is order items to link with order to input into erpnext.

This error was just an execution timeout so I extended that to work with it.

**Comment by Myddleware** [comment]
Thanks for your feedback. 
That's a great news, so we hope we can get it all sorted out quickly.

For information, most of Myddleware users use connectors like Prestashop, Salesforce, Vtiger, ERPNext, SuiteCRM, database and Moodle ; but no many people use Magento. So we haven't many feedback about Magento connector, this is why some module  might have bugsin the new version.

So we will use your feedback to fix the bugs and make everything work in Myddleware 3 (branch https://github.com/Myddleware/myddleware/tree/upgrade_symfony_4.4.18 ). Myddleware 3 is based on Symfony 4.4 and not 3.4, which is the framework for Myddleware 2 .

Launch of Myddleware 3 is scheduled for late August.
 
Thanks for your help.

**Comment by ModeBan** [comment]
@Myddleware would version 3.0 be functionally stable enough to install and use?

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Myddleware 's core is tested OK but jus a few connectors are tested OK. And ERPNext hasn't been tested yet. It should work but we aren't 100% sure yet.

**Comment by ModeBan** [comment]
@Myddleware okay so how do I install it haha?

**Comment by stlgaits** [comment]
Hello @ModeBan , if you want try out Myddleware 3 before it's released, there are 2 ways to install it at the moment. Either you can type all commands from a terminal or you can setup the project and the use the installation wizard we've created. Here's the procedure : 

# Myddleware 3.0 installation process

## From Git using a terminal

`git clone -b upgrade_symfony_4.4.18 git@github.com:Myddleware/myddleware.git`

or
`git clone -b upgrade_symfony_4.4.18 https://github.com/Myddleware/myddleware.git`

### installation

Go into myddleware subdirectory with this command : 

	cd myddleware

### check requirements before installing

	symfony check:requirements
WARNING : You need the symfony CLI to be able to run this command

### install dependencies

	composer install

### build assets

	yarn install

### set up your database

manually create a .env.local file at the root of the project (inside myddleware folder) containing environment variables, more particularly your database connection  : 

DATABASE_URL="mysql://username:password@host:port/databasename"
APP_ENV=prod
APP_DEBUG=false
APP_SECRET=Changethissecrettowhatyouwant
	
For example for a local setup :
DATABASE_URL="mysql://root:@localhost:3306/myddleware?serverVersion=5.7"
APP_ENV=prod
APP_DEBUG=false
APP_SECRET=Thisismypersonalappsecret

### connect to database

	php bin/console doctrine:schema:update --force

### load Myddleware fixtures 

	php bin/console doctrine:fixtures:load --append

### create your Myddleware credentials

	php bin/console myddleware:add-user 

You will be prompted to add your username, email and password.
You can still add a role to your user after its creation with the command : 

	php bin/console myddleware:promote-user <email> ROLE_SUPER_ADMIN


The installation process is now complete. You can login to Myddleware using your credentials in your browser.

## Using the installation wizard

The download procedure will have to be done with Git (see above) for now as Myddleware 3 is still under development, but in the future an archive will be downloadable for those who do not have access to a terminal with Git. You therefore still need to : 
- git clone -b upgrade_symfony_4.4.18 https://github.com/Myddleware/myddleware.git
- composer install
- yarn install
- yarn build

If everything went well, you can now close your terminal and go to your web browser at your Myddleware URL.  Go to 
Go to  http://yourdomain.com/yourmyddlewarefolder/myddleware/public
Or http://yourdomain.com/yourmyddlewarefolder/myddleware/public/install/requirements
If everything is OK, click on next, you will be taken to the database setup page.

#### set up your database
Here, fill in the form with your database information. Please make sure that your database already exists before filling in the form. Click on ‘Save’, then ‘Next’. 

#### connect to database & loading Myddleware fixtures
Follow the instructions from the wizard.

#### create your Myddleware credentials
You now need to fill in the form to create your Myddleware user credentials. Once this is done, you will be redirected to Myddleware. The installation process is finished. 

N.B. : Once the installation is complete, you will not be able to go back to these pages (all 5 steps). If you need to add another Myddleware user, you must go into your myddleware/myddleware directory and type the following command in a terminal window : 

	php bin/console myddleware:add-user

If you want to add a user with ROLE_SUPER_ADMIN, you need to type 

	php bin/console myddleware:add-user --superadmin


## Please bear in mind this version of Myddleware is still being tested and hasn't yet been released officially. Therefore I recommend to git pull on a regular basis to get the new features and bugfixes as they come along. Let me know if you have any questions or issues.

**Comment by ModeBan** [comment]
Sounds good @Myddleware 

The order items seems to be missing from the magento connector

**Comment by stlgaits** [comment]
Yes indeed, the products module is missing too. I will be fixing this this afternoon.

**Comment by stlgaits** [comment]
Hello @ModeBan , I've got a quick question since you're using Magento 2.4. I just got my new Magento 2.4.2. which now automatically comes with Two Factor Authentication. Myddleware doesn't support 2FA yet so I was curious as to how managed to get your Magento connector working without 2FA. I  found this :
https://github.com/markshust/magento2-module-disabletwofactorauth
but when I try to install it from my terminal, I'm hitting a wall as I get the following message : 

**Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
    Authentication required (repo.magento.com):**
And it then prompts me to enter a username and password, but I'm not sure which.
I've followed the procedure below but it didn't make any difference  : 
 https://devdocs.magento.com/guides/v2.4/install-gde/prereq/connect-auth.html

So I was wondering whether you'd managed to disable 2FA in a different way (or this one and would know what I could do)? For now, with 2FA  I still can't test my products and orders items modules additions.
TIA

**Comment by ModeBan** [comment]
Hey @EstelleMyddleware 

That's actaully a very annoying thing.

you can disable it by running  "php bin/magento module:disable Magento_TwoFactorAuth" in the root directory of the magento install and that will disable that module.

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Thanks for this command, it works. @EstelleMyddleware  will be able to work on this tomorrow.
We 'll keep you posted.

**Comment by ModeBan** [comment]
Hey @Myddleware @EstelleMyddleware I have installed Myddleware 3 and so far seems to be working fine i have tested the connector Magento 2 and ErpNExt to send data across and it seems fine so far.

Let me know when I can test the Sales Orders / Order Items modules :D 

Thanks guys

**Comment by Myddleware** [comment]
HI @ModeBan , Thanks for your precious feedback. We are happy that ERPNext is working fine on Myddleware 3.
@EstelleMyddlewarewill work on Magento in a few hours (Europe timezone).
We will keep you posted.

**Comment by stlgaits** [comment]
@ModeBan thank you very much !!! I've added the Orders Items & Products modules and tested them, it should now be operational, you simply need to git pull. Let me know if there are any unforeseen issues.

**Comment by ModeBan** [comment]
Hey @Myddleware @EstelleMyddleware 

Thanks so much for this, could you test that the sales orders pulls in order items? i cant seem to get it to work.

is this correct for the relation?

![image](https://user-images.githubusercontent.com/21164341/126612301-5080bf49-acae-479f-9922-6d939f5f3649.png)

**Comment by stlgaits** [comment]
For the relationship, you should have something like this in **Orders Items**  : 
![image](https://user-images.githubusercontent.com/74190794/126624541-863cdd2b-3c05-4d66-893a-5626c4cb342b.png)

**Comment by ModeBan** [comment]
Would you be able to setup a sample to erpnex t?

I can't seem to make it work.

**Comment by ModeBan** [comment]
Hi,

Would it be possible to appemd an item to items manually?

I have shipping charges but erpnext won't take shipping charges so I'd like to create and order line item manually along with the rest of the items

**Comment by Myddleware** [comment]
Hi @ModeBan 
We will prepare a template for you because the order creation in ERPNExt isn't very simple. You have to use a "child" relationship. 

So what I said to you about the relationship order and orderItem was wrong for ERPNext. It is usually right for CRM applications but not forERPNExt. I forgot it sorry. ERPNext doesnt' accept that you create an order (header) without OrderItem, so we have to create the order and orderItems in the same time.

In this case we need to setup a child relationship. So when Myddleware will read a new order from Magento to ERPNExt, Myddleware will read all the Order lines of your current order from Magento too, and merge the current order data with the order lines before sending it to ERPNExt.

And you will be able to filter the orderlines if you don't want to send shipping line to ERPNExt.

I 'll keep you updated.

**Comment by ModeBan** [comment]
Hi @Myddleware 

That's good thanks for that. Let me know when that's done.

Could you incorporate a shipping line into the order items that's pulled from the shipping details in magento order?

**Comment by Myddleware** [comment]
Hi @ModeBan ,
We have fixed a few bugs in Magento connector and created a template with 4 rules (customers, products, order, and orderItems). Please execute a git pull to get all changes made into the branch upgrade_symfony_4.4.18

Then generate a template by creating a new rule and selecting this template : 
![image](https://user-images.githubusercontent.com/11330301/126813680-d1f9a067-b7f4-4415-966e-c35aaa4844d3.png)

It will generate 4 rules : 
![image](https://user-images.githubusercontent.com/11330301/126814322-4078ff87-f11b-41c9-bfda-9ee8a6a5f326.png)
You can use these rules (and modify them) to sync your data, or just open it to see how we have created them and modify your existing rules.
Please enable all the rules exept the rule "OrderItem to ERPNExt". This rule shouldn't executed on its own, it will always be executed by the rule "Order to ERPNExt".

The main difficulty in this interface is on this relationship : 
![image](https://user-images.githubusercontent.com/11330301/126814253-5796d011-d41d-42e9-93e6-037bf8e19a6f.png)

Then, if you want to add a shipping line in your sales order, please follow these steps. We haven't added it to the template because it takes to create manually an item in ERPNext.

1. Create a shipping item in ERPNext like this : 
![image](https://user-images.githubusercontent.com/11330301/126815070-a3a20f1c-ad79-46df-9813-6fecd2196f52.png)

2. Create a new rule in Myddleware based on the Magento's order where shipping data is stored : 
![image](https://user-images.githubusercontent.com/11330301/126815218-11803d52-c0e8-402f-b890-9cef4183010a.png)

3. Map at least these fields : 
![image](https://user-images.githubusercontent.com/11330301/126815372-c97b64f1-6006-41ff-b343-9da4a1eb5bf5.png)

4. Item code is a very important field to be mapped, you have to set exactly the same name that you have set in ERPNext : 
![image](https://user-images.githubusercontent.com/11330301/126815548-3757379f-1a7d-4d68-8bf4-4ada3b73c16a.png)

5. Save your rule but don't enable it (like the order item rule, it will be executed by the sales order rule). Then open your Sales order rule, go to the relations tab, and go to the bottom on the page (Parent relationship area). Please add this relationship :
![image](https://user-images.githubusercontent.com/11330301/126815917-3d7fccb1-e971-429a-8b0f-6c1aa4b6a607.png)

Here is what this relationship do : when a sales order will be read by Myddleware (by the rule sales order), Myddleware will use your rule "Shipping order to ERPNext" to search into Magento the salesOrder corresponding to the current order_id. Then Myddleware will generate a document for the rule "Shipping order to ERPNext". Then Myddleware will add this document as an orderItem into the order that will be sent to ERPNExt.

6. When I execute the rule Salesorder on demo data, I have this order into Magento : 
![image](https://user-images.githubusercontent.com/11330301/126816612-0ea15800-c206-498f-ac26-a5921997845a.png)
 
7.  Here is the one created by Myddleware in ERPNext: 
![image](https://user-images.githubusercontent.com/11330301/126816709-047a4ca2-b811-42ac-9477-8d7f9fc13458.png)

8. Here is the document in Myddleware, you can see the 2 order items linked as child document :
![image](https://user-images.githubusercontent.com/11330301/126817577-595718d3-d551-4183-8c4e-25cdc72ede31.png)

It was a very long message but we hope it will help you.

**Comment by ModeBan** [comment]
Thanks for that I'll have to try it and I'll let you know.

Could you add the .env file to the gitignore file?

**Comment by ModeBan** [comment]
Hey @Myddleware 

How would I incorporate the address for the order/customer?

**Comment by ModeBan** [comment]
Hi @Myddleware im getting this now with the template.

Child document in error (rule 60fc56ef3b80a) : Transfer id 60fc5ae8b2cb46.64817073 : Error, status transfer : Error_transformed The child document has not be saved. Check the log (app/logs/prod.log) for more information. /var/www/html/myddleware/src/Manager/DocumentManager.php Line : ( 1033 )Status : Error_checking

**Comment by stlgaits** [comment]
> Thanks for that I'll have to try it and I'll let you know.
> 
> Could you add the .env file to the gitignore file?

Hi @ModeBan the .env file isn't in gitignore as it serves as a template, but it is actually overridden once you install Myddleware by a .env.local file that contains your actual secret environment variables.

**Comment by ModeBan** [comment]
Hi @EstelleMyddleware so would I need to create a .env.local file?

**Comment by stlgaits** [comment]
It should already be there if you've followed the procedure above, but if you don't have one then yes create it and put your database connection and secret variables in there

**Comment by stlgaits** [comment]
Btw I'm testing the template and I am getting the same issue as you so I will be trying to solve it and let you know once it's fixed

**Comment by ModeBan** [comment]
Sounds good @EstelleMyddleware thanks I'm looking forward to getting this setup :D

**Comment by stlgaits** [comment]
Ok, so I know what's the issue. It's to do with your Products rule, if I understand correctly you'd already synced your products to ERPNext. So, there are a few solutions for this problem : 
- either you can go to you Order Items relationship section here and change the rule to your old Products rule instead of the template one  and execute all the rules again : 
![image](https://user-images.githubusercontent.com/74190794/127003913-db0dcf9d-5fea-405a-b2ed-c063fcccf372.png)
- or you can git pull  as I've added a bit of new code and then you need recreate the template rules you will see that there will now be 'item_code' in the fields to avoid duplicates section of your Products rule (in the template) and execute all the rules again : 
![image](https://user-images.githubusercontent.com/74190794/127004225-43a1fb1a-176d-46ff-a61b-30e89378deab.png)
Let me know if  you have any questions.

**Comment by ModeBan** [comment]
Hey @EstelleMyddleware,

How can I customize the template?

**Comment by ModeBan** [comment]
@EstelleMyddleware 

I'm getting this here error,

All records read have the same reference date in rule Magento to Erpnext ( Products ). Myddleware cannot guarantee that all data will be read. Job interrupted. Please increase the number of data read by changing the limit attribute in job and rule classes.

i think its just timing out, im trying to pull the whole products list, how can i allow this to execute?

**Comment by Myddleware** [comment]
Hi @ModeBan ,
You have probably installed Magento with sample data.  In this case, you have probably 2046 products in your Magento instance. The problem is that all of these products have the same modified date. And the number of records (products here) with the same modified date must be lower than your rule limit, otherwise Myddleware can't be sure all the records has been read. 
So you should put a limit greater than 2046 in your rule. However I don't think Magento allows you to read more than 2000 product in 1 call. 

The problem here is the sample data because all the products have been created at the same time. 

A simple workaround is to change a little bit the modified date of all your products. You can run this query in your Magento database : 
`UPDATE mghm_catalog_product_entity SET updated_at = DATE_ADD(updated_at, INTERVAL (FLOOR(RAND() * (-1000))) SECOND)`

It is possible that the prefix of the table mghm_catalog_product_entity is different from mghm.

Then you can set your reference date of your product rule in the past and execute your rule again. If the limit of your rule is still 100, your will need 21 executions to read all you.

Hope it will help you

**Comment by ModeBan** [comment]
When you say 21 executions do I have to set the date back to the same one in the past?


Thanks for getting back to me 
@Myddleware

**Comment by Myddleware** [comment]
Hi @ModeBan , 
You just have to set the reference date of your rule before the first execution, then myddleware will automatically update this reference date.
Hope it helps

**Comment by ModeBan** [comment]
As a future reference the curl timeout in the magento.php solution file was the issue that stopped the transfers above 1000k

@Myddleware @EstelleMyddleware
