### ISSUE TITLE
millisconds lost in date reference

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#566]
Hi,
we have this scenario.
records with date reference in this format:
2021-09-18 10:04:50.303
But when the rules run date reference of last run is saved in this way:
![image](https://user-images.githubusercontent.com/6990139/135055601-1b1b5dbf-8ae4-463e-b533-cf2a45d479bf.png)
The result is that in following run are processed same record every time.

We are connecting a mssql Db to Vtiger.

**Comment by stlgaits** [comment]
Hello @simonetravaglini  Could you confirm that you are sending records in this direction ?
Source:  MSSQL 
Target:  Vtiger

**Comment by simonetravaglini** [comment]
@EstelleMyddleware yes I confirm.

**Comment by simonetravaglini** [comment]
@EstelleMyddleware @myddleware-dev have you tips for me? ;)

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Sorry busy period ;)

When we check the code, the MSSQL read function should return the date with microseconds :  2021-09-18 10:04:50.303, and store it as date_ref. So the date in your rule should have the microseconds.
The only thing I see is maybe a custom code that change the date format . And if I remember well, we have guide you to develop some custom code.

You probably have a MSSQL custom file for your connector (should be the file src\Myddleware\RegleBundle\Custom\Solutions\microsoftsql.php or src\Myddleware\RegleBundle\Custom\Solutions\database.php),

If yes, could you send us these files if one of these exists ? Thanks.

**Comment by francescobianco** [comment]
Hi @Myddleware @EstelleMyddleware 

The only custom code we have for dare_ref management is it:

```
    public function read($param)
    {
        // Redefine reference date format (add milliseconds)
        try {
            $date = new \DateTime($param['date_ref']);
            $param['date_ref'] = $date->format('Y-m-d H:i:s.v');
        } catch (\Exception $error) {
            // Ignore problem on date_ref
        }

        // Call standard read function
        return parent::read($param);
    }
```

This code has the purpose of ADDing microseconds when missed on source

**Comment by Myddleware** [comment]
Hi @francescobianco ,
We have checked the code and the reference date should be displayed as it is returned by the read function. There is no date transformation when Myddleware save the reference date in the database here https://github.com/Myddleware/myddleware/blob/58cc2036e23f86f15f69a2db62d149515384fc2d/src/Myddleware/RegleBundle/Classes/rule.php#L390

Could you check in debug what is the value of this variable $this->dataSource['date_ref']  before it is saved in the database ? 
If there is no microsecond there, we will be able to check step by step this variable to find where the microseconds are lost.
Thanks.

**Comment by francescobianco** [comment]
Hi @Myddleware , we have an update about our problem with MILLISECONDS. This is a long Story. I report it to you due to take notes for future problme with this:

## The long Story

In PHP world we have two different way for access on MSSQL database 

1. PDO with SQLSRV <https://www.php.net/manual/en/ref.pdo-sqlsrv.php>
2. PDO with DBLID <https://www.php.net/manual/en/ref.pdo-dblib.connection.php>

For some reason, we sometime swith from SQLSRV (our favorite) to the DBLIB (called the B plan)
I this specific scenariou we have DBLIB. 

Not for all but just in this case the DBLIB driver remove milliseconds from DATETIME field.
It is strange, could be related to a bug of DBLIB or a particular combination of Server Versions

## Problem in the real

If I query a record from DB

```
SELECT name, last_time FROM People LIMIT 1;
```

the result is
```php
array(
 'name' => 'Francesco',
 'last_time' => '2021-12-21 12:00:00', // without milliseconds
)
```

But in the database data is the follow

| Name | Last Time |
| -------- | ------------- |
| Francesco | 2021-12-21 12:00:00.120 | 

## The magic solution

The magic solution is base on extract millisencond with additional field like this

```
SELECT name, last_time,  DATEPART(ms, last_time) AS last_time_millis FROM People LIMIT 1;
```

The result is this

```php
array(
 'name' => 'Francesco',
 'last_time' => '2021-12-21 12:00:00',
 'last_time_millis' => '120',
)
```

Magically if you extract millisencond apart it appear.

## Finally

Usign this workaroud we have put in place custom code to append milliseconds on extracted record beforect myddleware store the NEXT 'date_ref' on DB.

> We wanted to tell you the facts in the hope that it will help you in the future.

**Comment by Myddleware** [comment]
Thank you so much @simonetravaglini @francescobianco  for your feedback and the explanation of the solution you found.
