### ISSUE TITLE
Cannot remove field in mapping when the field has special charcters

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#577]
Take this as an example:

![image](https://user-images.githubusercontent.com/36896420/138732507-95bf0e12-e3a9-48d5-a1bc-43581fcc0c26.png)

The field `¿Por donde le gustaría ser contactado?` cannot be removed by double clicking on it, unlike fields without special characters.

This is closely related to #573

**Comment by stlgaits** [comment]
Very specifically, this issue is linked to the upside down question mark character only, which isn't recognised. 
Here is a partial fix in Myddleware 3.0 hotfix, but still trying to fix this properly. 
https://github.com/Myddleware/myddleware/commit/7e44e99c967ea08ca2ec91482b95032549be3639
With this fix for now, you can remove the field from the fields mapping, but the problem is moved to the filters tab where the `<li>` 's ID isn't recognised, for example : 
![image](https://user-images.githubusercontent.com/74190794/138882421-117fc216-cb70-4cdc-8dba-052ab40a6abd.png)
and therefore the field is still present when it shouldn't be.

**Comment by AlexMyddleware** [comment]
fixed in this commit

https://github.com/Myddleware/myddleware/commit/b157885b5625887a88edfafd1a383cfddb890b37

double clicking to remove field also works.


![image](https://github.com/Myddleware/myddleware/assets/106162060/3107c9cb-11ea-4c5b-a3a6-42a586221bda)
