### ISSUE TITLE
FTP connector file scheduler

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#578]
Hi,
we are using FTP file with txt (you did a customization for us) file, but facing an issue.
Seems that scheduler load the file with more recent date. But suppose I load 3 file at same time, then the flow fail and skip one at least.
I suggest a different beahaviour. 
It should load the oldest file with TXT extension, then when have finished to get data from file it shuold change the name of file.
What do you think about?

@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini,
I see the issue. However I think that the solution won't work with our connector (but thanks for the proposal) because Myddleware has 2 ways to read new data : 
 1) Like in your case : if one or several new files  are posted in the directory, Myddleware will read these new files
 2) Second way : if new lines are added into an existing file, Myddleware will detect that the file has been modified, then Myddleware will read the new lines from the file (Myddleware store each line where it has stop to read for every files)

If we change the name of the file, the second way won't work anymore.

However, you are right, if there are 3 files added at the same time and if one of them failed, some data won't be read. I think that what we should do is : if a file failed to be read then we create a flag into Myddleware to indicate that the file couldn't be read. And Myddleware will try to read the file again during the next run.

What do you think ? 

@francescobianco @EstelleMyddleware
