### ISSUE TITLE
Prestashop connect with sugar

### ISSUE THREAD

**Issue by ftpuche** [Myddleware/myddleware#59]
Hello,

I am trying to connect prestashop with sugar crm, I wanted to ask if there are predefined templates for the most important entities such as clients, orders, products, etc.
Thank you very much in advance

**Comment by Myddleware** [comment]
Hi,
Thank you for contacting us. 
We have a predefined template for SuiteCRM but not for SugarCRM yet. Unfortunately, the quote and product modules are differents between SugarCRM and SuiteCRM (even if SuiteCRM is a fork of SugarCRM). 
So we have to build a new one and share it with the community. 
Give us 2 days and we will build it for you ;). OK for you ?
See you soon.
Stéphane Faure

**Comment by ftpuche** [comment]
Hello, for me there is no problem,
Thanks in advance,

**Comment by Myddleware** [comment]
Hi,
We have created a template which send : 
 - Prestashop Customers to SugarCRM Contacts and accounts
 - Prestashop Products and Categories to SugarCRM ProductTemplate and categories
 - Prestashop Orders and Order lines to SugarCRM quotes, quotes item line and product bundles (product groups containing the order lines in Sugar)

We had to update the SugarCRM connector which will be available in Myddleware version 2.3.3. So you will have to replace the file manually because the current version of Myddleware is the version 2.3.2.

So to use this template, please follow these steps (if you can't wait the version 2.3.3 which will be lauched end of next week) : 
 - Make sur you use Myddleware version 2.3.2. Here are the steps to update Myddleware : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware
 - Add the file prestashop_sugarcrm_customers_orders_products.yml (in attachment) in the directory <Myddleware>\src\Myddleware\RegleBundle\Templates
 - Replace the file sugarcrm.php (in attachement) in the directory <Myddleware>\src\Myddleware\RegleBundle\Solutions
 - Then generate your rules from the template, 11 rules will be created
 - Then edit a rule and save it (it is a workaround for a bug to finish the template generation, this bug will be fixed in the next release)

[file_template_sugar.zip](https://github.com/Myddleware/myddleware/files/1605234/file_template_sugar.zip)

Then you can modify the template to meet your needs. For information, we create templates just to help you to start with rules and relationships. This is not a complete interface. You will have to modify the rules to meet you needs.  

Just let you know that when we send data to the quotes via the REST API, some calculated fields (like total, subtotals) aren't refreshed automatically. You have to edit and save the quote to refresh these fields. Please let us know if you find a way to automatically refresh these fields. Thanks.

Contact us if you need more help.
Best regards,
Stéphane Faure

**Comment by ftpuche** [comment]
Hello good day,
If I find a way to update the data I will let you know.
Thank you very much
