### ISSUE TITLE
Relations do not register

### ISSUE THREAD

**Issue by CamillePMyddleware** [Myddleware/myddleware#590]
![Relations](https://user-images.githubusercontent.com/95077335/143587685-1cd99810-dbd9-4b7a-afb4-ee8c7a979123.JPG)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/143885217-c4bd778f-800e-4580-8c4d-a43a2a389854.png)
The problem came from a missing class in frontend table of relationships. I have fixed it, however this makes me think that an enhancement should be made in how we generate / save rules parameters, since here a simple frontend modification ended up breaking up the whole workflow without even triggering a single error along the line.
