### ISSUE TITLE
SuiteCRM to Moodle Users Connection issue

### ISSUE THREAD

**Issue by thewebsitefactorylondon** [Myddleware/myddleware#60]
Hello Myddleware Team, Hope you are well. I have an issue connecting SuiteCRM (Contacts) data with Moodle (Users). So far I completed following steps from this source;
https://myddleware.github.io/myddleware/#/connectors_credentials

1) 1.2 and 5.3 successfully configured as instructed in the link above
2) Rule created under Roles and activated (with duplicate record check on username)

When I run the Rule, it gives following errors;
![image](https://user-images.githubusercontent.com/28488395/34530650-bceb6f02-f0a7-11e7-93aa-7e7e957f68c7.png)

Here is the detailed error (_invalidparameter : Invalid parameter value detectedFailed to send document. Status : Error_sending_)

![image](https://user-images.githubusercontent.com/28488395/34530808-3239373a-f0a8-11e7-89f4-d856ba6a5e5b.png)

and this;

![image](https://user-images.githubusercontent.com/28488395/34530854-503354aa-f0a8-11e7-8e6d-d0d683787e9c.png)

I'd be grateful if you kindly provide a solution for this connector. Your help will be much appreciated. Many thanks in advance for your help.
Best wishes,
Mohamad

**Comment by Myddleware** [comment]
Hi Mohamad,
We are very well, thanks. And we hope that your are well too.
Thanks for using Myddleware.
 
Unfortunately the error returned by Moodle hasn't much detail. So could you try to create the user manually with the same data that you have in your transfer. Moodle should give you an error too with  more detail, for example, the password is too short, or username has space, a user is alreday existing with the same email address...
When you have the error, you could change your data transfer and your rule.

The good news is, if Moodle returns this error, it means that your connection is working. It is better to get an erro than nothng ;).

Could you tell us if your problem is solved ? Thanks.
Best regards,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Dear Stéphane,
Thank you so much for your prompt reply. I tried creating a user manually in Moodle with given data in SuiteCRM, it worked. I think I must have made some mistakes in creating rules maybe? Any other solution?

The only error I can see in log is; _Array ( [0] =&gt; Transfer id 5a4d044eb6ded5.95730761 : Error, status transfer : Error_sending. invalidparameter : Invalid parameter value detected )_

Thank you very much for your help!
Best wishes,
Mohamad

**Comment by Myddleware** [comment]
Thanks Mohamad,
Could you show me the detail of a data transfert if it is a test data (don't share client real data). Then we will test these data in our Moodle.
Thanks.
Best regards.
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Dear Stéphane,
Sure, following details we have.

First name: First
Last name: Last
Username: abcdefghij081991
Password: ChangeMe123*
Email: standard Gmail/Hotmail/Yahoo account

Once again thank you for your kind support!
Best wishes,
Mohamad

**Comment by Myddleware** [comment]
Hi Mohamad,
I have tried it with our test Moodle  and your data works :
![transfer_user_moodle](https://user-images.githubusercontent.com/11330301/34535248-c29b38e8-f097-11e7-9b2d-d0dfdcb5e694.png)
 
So the problem is maybe in Moodle configuration. 
What is the version of your Moodle ?
Could you change the log level to debug (just during the time you are debugging). To do that go to  Site Administration -> Development set "Debugging" And select "DEVELOPPER" in "Debug messages". 
Once you have changed the log level, could you try to reload your data transfer (open the data transfer and click on reload). Then check your log in Site Administration -> Reports -> Logs.

Do you have more detail about the error ?

Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Thank you for your reply and continued support. I changed log level to debug and found following log report;
![image](https://user-images.githubusercontent.com/28488395/34563654-5407a6a0-f14b-11e7-954c-7b00dfa7b6d8.png)

I'm getting the same error _(invalidparameter : Invalid parameter value detectedFailed to send document. Status : Error_sending)_

I'm using the latest version of Moodle - Moodle 3.4+ (Build: 20171201) and SuiteCRM (SuiteCRM 7.9.8).

Could you kindly suggest all the steps you followed when you created the rule? Maybe I'm missing something in mapping both connectors.
Many thanks for your time and I look forward to hearing from you!
Best wishes,
Mohamad

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Just to let you know I did set following Functions in External Services
![image](https://user-images.githubusercontent.com/28488395/34564623-4ded7d2c-f14f-11e7-9677-d0d3a49f634c.png)
Are there any other functions that I need to add?
Thank you!
Mohamad

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Good news! Sorry to bother you again. I deleted old rules and created a new one and this time I connected ID Contact to ID Users in Step 5 (Relations). It worked!!

![image](https://user-images.githubusercontent.com/28488395/34565329-57411bba-f152-11e7-9784-6f9e075fccbe.png)

However, it created only one contact (first record on the list). Ideally, it should check all contacts and create users that do not exist in Moodle. Any suggestions?
Thank you!
Mohamad

**Comment by Myddleware** [comment]
Hi Mohamad,
Thanks for  this good news. If you want to read more data from Prestahop, you have to set the reference date in the past. Please have a look to this article : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters
Please let me know if it has solved this problem.Thanks.
best regards,
Stéphane

**Comment by thewebsitefactorylondon** [comment]
Hi Stéphane,
Many thanks for your prompt reply. I followed instructions you suggested, and it is working now. Great work!! Much appreciated your continued support. : )
Now my next step is to enroll students from SuiteCRM to Moodle. I'll try with similar steps to create a new rule and see if it works.
Hope you have a great weekend!
Best wishes,
Mohamd

**Comment by Myddleware** [comment]
Thanks for your feedback Mohamad.
Have a nice day.
Stéphane
