### ISSUE TITLE
Problem after relation ko

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#615]
Hi myddleware team,
I want submit following scenario we are struggling to solve.
We have to rules:
1 - RULE1
2 - RULE2 (every record is related with RULE1).
Sometimes from source the record from RULE1 related to RULE2 is available some second later.
This cause a relate OK. Then relation is avaiable and record of RULE2 is ok.
The problem is that we got every run a predecessor KO, also if relation now is ok.
I can share this screenshot:
![image](https://user-images.githubusercontent.com/6990139/149467414-b45a6456-1a27-4ff2-889d-af46a036c1b9.png)
[1] relation KO
[2] relation OK
[3] still predecessor KO

@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini @francescobianco ,
OK, I guess that the document with status predecessor_ko haven been created between 20:01:19 and 20:50:41, during this time your current document was in status relate_ko. Tell me if I am wrong.
Now if you run again your document in status predecessor_ko, they should run properly. Could you try ? 
If yes and if you don't want to run manually these errors, you can use the job rerunerror.
Please let me know if it helps.

**Comment by simonetravaglini** [comment]
yes you are right. as you can see in previous screenshot then record is ok... but then I get tons of relate ko also after relation is ok:
![image](https://user-images.githubusercontent.com/6990139/149482088-7191421e-1b2b-4b2d-848d-df4018298df2.png)

**Comment by Myddleware** [comment]
Ok @simonetravaglini  I see. I guess the Rule 2 reads all records every 5 minutes. So you have more errors generated than error closed using the program rerunerror.
What you can do here is running a task that will rerun all the documents with status error ou open for a specific rule. By this way you will be able to close every error for your Rule2.
Here is the command to run this tasks : 
`php bin/console myddleware:massaction rerun rule <id_rule> --env=background`

You can alse cancel or remove all the documents with status error ou open for a specific rule
`php bin/console myddleware:massaction cancel rule <id_rule> --env=background`
`php bin/console myddleware:massaction remove rule <id_rule> --env=background`

Please let me know if it helps.

For information, we plan to work on a real queue management in the next Myddleware version. When a document belonging to a queue will be send, it will unlock all the documents in the queue ( so all documents linked to the one sent).

**Comment by simonetravaglini** [comment]
@Myddleware after testing rerun from console then errors are not fixed, but he say again PREDECESSOR KO also if relation it's not still KO but now is ok.

**Comment by francescobianco** [comment]
I suspect that these records cannot be resolved by a RERUN because they are in an infinite Predecessor_KO condition. That is, every time he turns all the records have the Predecessor_KO and therefore no one is freed.
This how I mind it
![Presentazione senza titolo](https://user-images.githubusercontent.com/472171/150955111-296cefc6-4683-4918-936a-d8fa1ef3635f.jpg)

**Comment by Myddleware** [comment]
Hi @francescobianco  and @simonetravaglini ,
Could you check if there is a loop into the predecessor queue. I mean could yo check if a document with status predecessor_ko is linked to another on, maybe linked to another one.... and finally linked to the first one.
You can see the document linked in the logs which carries the predecessor_ko status : 
![image](https://user-images.githubusercontent.com/11330301/151071828-6377c7fa-a8f7-4955-b06e-440c53d0f82c.png)

Thanks.

**Comment by simonetravaglini** [comment]
@Myddleware 
Hi, 
I think yes, during my test I saw that i can find the origin of the error, that is a relation KO, but it's on another document I think, as you say.

**Comment by Myddleware** [comment]
Hi @simonetravaglini 
Sorry for the late answer. 
OK so there is no loop, that's a good news.  There should never be a loop.

In you case, I guess there is a relate_ko document. Then, because you read all data each time, a predecessor_ko is generated  for each new run.
What I advise you to do : 
 - 1) Fix the relate ko document
 - 2) Then cancel every document in predecessor ko linked to the relate ko that you have fixed. You can use the search document view by filtering by rule and "id source" (use the same source id than your relate ko document).
 - 3) then the next time a document is generated for this source_id, it will be send properly and not be blocked by the other predecessor_ko (because you have cancelled them).

Please let me know if it isn't clear.

**Comment by simonetravaglini** [comment]
@Myddleware I did it many times, it fix for some hours, but then it happens again becouse a new similar situation.
So I've this instance full of error also after data are ok. 
I mean, relation ko is fixed automaticaly, but error are generated also after fixed.
Not sure if i make the scenario clear for you.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I just check the open topic and I have seen that I didn't reply to you, sorry.
In you case we have to identify why the first relate_ko appends. Could you give me more detail about the first error which have the status relate_ko ? 
Thanks.
