### ISSUE TITLE
Microsoft database wrong password if has '%%'

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#622]
If database has '%%' into password it cannot connect from myddleware because myddlewre lose di value

**Comment by Myddleware** [comment]
Hi @francescobianco 
Thanks for this feedback, we will look into this.

**Comment by AlexMyddleware** [comment]
@francescobianco, i've looked into this problem, here is what i found:
in HttpKernel.php in the vendor files, the request is processed in the handleRaw function. At this stage, you can see that the fake password i used, which is %te%st%, is still intact.

![image](https://github.com/Myddleware/myddleware/assets/106162060/274070da-1c52-4818-8dbd-ab7b98f6f398)

however, at the very next line, the dispatcher,using the dispatch method, seems to be misinterpreting the character, resulting in the loss of the middle of the password

![image](https://github.com/Myddleware/myddleware/assets/106162060/ee9dda59-420e-4814-9f13-61ac65c49e64)

i assume this is what you mean, and if that's the case, maybe you can intercept the request prevent it from being modified. 

However I tried to modify the string manually in the debugger for testing, but it gets transformed later. You would have to modify the symfony code at several differente stages to preserve the state of your password.

 I would suggest avoiding using % in the password instead, because i'm not sure we will be able to help you, since this is a symfony issue and not a myddleware issue.
