### ISSUE TITLE
more modules in rule

### ISSUE THREAD

**Issue by ATrogischDev** [Myddleware/myddleware#71]
Hi,
Is it possible to create two rules in dependence or two modules in on rule? 
What I need is a conection between prestashop and moodle. I want to enrole an user in an course in moodle, but maybe he dosent exist, so I need the option to create a new user first in this case.

thanks for help

**Comment by Myddleware** [comment]
Hi,
Yes, you have to create several rules. But before moving forward, could you tell me if each Prestashop product is a Moodle course ? 

If yes, you should use 4 Prestashop modules : 
 - The e-shop s customer
 - The customers orders
 - Detail of an order
 - The products

And you should use 3 modules in Moodle : 
 - Users
 - Manual enrolment
 - Courses

In this case, you will have to create rules with many-to-one relationship as you have 4 Prestashop modules for 3 Moodle modules. You can have a look to this chapter to have more informations : https://myddleware.github.io/myddleware/#/advanced_usage?id=use-case-2-many-to-one-relationships

Your interface won't be very easy to build. And we would like to build an interface template for your needs as other people will have the same.

So please let us know if you can manage to build the interface by yourself, and we will show you how to generate the template. Otherwise we will help you to build this interface.

Have a nice day.
