### ISSUE TITLE
Auth problem on Myddleware API (version 2.5.7)

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#711]
We try to use Myddleware API with the folling script
```shell
#!/usr/bin/env bash

myddleware_url=http://myddleware1.acme.com

token=$(curl -s --location --request POST "${myddleware_url}/app.php/api/v1_0/login_check" \
     --header 'Content-Type: application/json' \
     --data-raw "{\"username\":\"admin\",\"password\":\"xxxxxxx\"}" | cut -d'"' -f4)

synchro=$(curl -s --location --request POST "${myddleware_url}/app.php/api/v1_0/synchro" \
     --header 'Content-Type: application/json' \
     --header "X-Authorization: Bearer ${token}" \
     --form 'rule=xxxxxxx')

echo "$synchro"
```

But it still respond with 

```shell
{"code":401,"message":"Bad credentials"}
```

Obvilsuly we use the right password, and token seems good as structure. but it is not authenticated
From the server side we have correctly received the token as expected.

Please can you confirm it works as espected?

**Comment by stlgaits** [comment]
Hello @francescobianco , I've tested this on my side and for some reason it seems that it **only works in dev environment** for the login_check path, indeed I got this URL to work on my localhost : 
http://localhost/myd257/myddleware/web/app_dev.php/api/v1_0/login_check
which returned me the JWT 
and then I passed the token to the following URL
http://localhost/myd257/myddleware/web/app_dev.php/api/v1_0/statistics
and I did get the results I was expecting 
![image](https://user-images.githubusercontent.com/74190794/162703794-a8d3bcba-1097-4273-a9d3-1e6a2735d579.png)
I'm not sure where the error is coming from but if you could test using app_dev.php instead of app.php for now and let meknow if that worked that would be great.

**Comment by francescobianco** [comment]
@EstelleMyddleware please. Go Ahead with your test try to call a SYNCHRO api and show me the results

The problem is NOT at login stage BUT at SYNCHRO stage

**Comment by stlgaits** [comment]
Hi @francescobianco , I have no issues with synchro in dev environment like I mentioned before. Please check out the result of my synchro test in dev environment : 
![image](https://user-images.githubusercontent.com/74190794/162727333-6a4084f2-2548-458a-a550-b226fffb941d.png)
As opposed to a 'wrong' error message which shouldn't be there in prod environment : 
![image](https://user-images.githubusercontent.com/74190794/162727475-1a641279-0ae6-4f3e-9551-da33ff81903e.png)
Therefore I think you should give it a go and try to test by changing app.php to app_dev.php for the moment before we get a chance to fix the bug in prod environment. 
Let me know if you get a similar result or if the error remains the same.

**Comment by francescobianco** [comment]
Eureka!

The problem was related to the usage of a standard Authorization header. To work with specific Apache version we need place this on HTACCESS file

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

This is reported into this https://github.com/symfony/symfony/issues/19693

**Comment by Myddleware** [comment]
Hi @francescobianco , thank you so much.
@EstelleMyddleware , could you have a look into this and check if we have to update the htacess file in Myddleware 2 and 3 ?
Thanks

**Comment by stlgaits** [comment]
Hello @francescobianco  @Myddleware , after reading carefully, if I understand correctly (please feel free to correct me if I'm wrong), this is a quite specific issue and a modification was rejected by the Symfony team (see https://github.com/symfony/symfony/issues/19693#issuecomment-343681561) for that reason at the time (bear in mind that since we're referring to Myddleware 2.5.7, we're on Symfony 3.4 version therefore the related issue dates back to 2016, which is quite a long time ago now), therefore I don't think we should update our .htaccess file, given that it is based on the standard Symfony file using symfony/apache-pack and we haven't encountered any issues except this one here. Let me know what you think @francescobianco
