### ISSUE TITLE
Issue creating rule with MySQL Connector

### ISSUE THREAD

**Issue by seseso** [Myddleware/myddleware#76]
I've created a MySQL connector but when I try to use it in a rule, the list of available modules (Tables) is empty, both on src or target.

The database selected in the connector have tables.

**Comment by Myddleware** [comment]
Hi,
The user you have used to create the connector. Does this user have access to the tables ? 
Best regards,

**Comment by seseso** [comment]
Hi,

Yes, he has grants on all tables. 
I even tried the root user without success.

**Comment by Myddleware** [comment]
Alright,
Are you developer and do you know how to debug PHP ? If yes I could guide you to debug in Myddleware and try to analyse this problem
 
Otherwise, if your database if a database with test data, you could use our contact page to give us your database access (http://www.myddleware.com/contact-us). Then we will debug the connection to see what is the problem.

**Comment by seseso** [comment]
I have a local instalation so I can't give you access to the database but
if you could send some guidlines to them and report back the results. I
will only be able to do that on monday.
Thanks!

**Comment by Myddleware** [comment]
Hi,
We have tried a local installaion with Xampp  and everything is working as expected. We can see the tables of our local database with MySQL connector.
![local_mysql](https://user-images.githubusercontent.com/11330301/35772335-4e2e14f6-0912-11e8-9aac-1d34e64a7893.png)

Are you using Xampp ?
Best regards,
Stéphane
