### ISSUE TITLE
[Myd3] Vtiger connector doesn't have delete function anymore

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#769]
In myddleware3 vtiger connector doesnt' have anymore delete function.
I mean this one in M2:
![image](https://user-images.githubusercontent.com/6990139/178215153-0ad6a033-c9b7-4e23-866a-a5f1f1b37b75.png)

Also "Read all at each run" is missing

@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini  and @francescobianco ,
I can see the delete function in Vtiger connector here : https://github.com/Myddleware/myddleware/blob/7601bf750f14f6b6c23a6ea67d59c3b71fe38ab7/src/Solutions/vtigercrm.php#L663

I thing that "Read all at each run" at each run was a custom code for you in Myddleware 2, isn't it ? If yes, the cade has to be adapted to Myddleware 3, we can guide you for that.

Best regards.

**Comment by simonetravaglini** [comment]
@Myddleware after debugging we found that the issue was related to the fact that delete function was not "ON" on source connector (MSSQL). 
@francescobianco would you like to share details and commit the way we solve?

**Comment by francescobianco** [comment]
Hi @Myddleware this was related to the fact:

By default MySQL database has deletion flags enabled, visible here https://github.com/Myddleware/myddleware/blob/7601bf750f14f6b6c23a6ea67d59c3b71fe38ab7/src/Solutions/mysql.php#L37

Otherwise for MicrosoftSQL it NOT by default 
https://github.com/Myddleware/myddleware/blob/7601bf750f14f6b6c23a6ea67d59c3b71fe38ab7/src/Solutions/microsoftsql.php#L36

In our version we have add it by default
https://github.com/opencrmitalia-official/myddleware/blob/1c08c9374bc404d03aefc8dd91458bedf8fad79c/src/Solutions/microsoftsql.php#L38

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Because you have tested it, we will add it to Myddleware standard in the next release. 
Thanks you very much.

**Comment by Myddleware** [comment]
Here is the commit : https://github.com/Myddleware/myddleware/commit/34ca00d30299cba014602a6a8d633f981580143d
