### ISSUE TITLE
[MYD3] Cron: sequence of rules

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#813]
Hi,
in myd2 scheduler I had possiblity to set priority, to determine sequence of rule.
In myd3 with cron how could work?
Suppose I have ten rules that runs every 5 minutes, how I can set sequence?
If the sequence followed is creation, it should be possible to modify from frontend

**Comment by simonetravaglini** [comment]
@Myddleware did you had time to analize this issue?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
The bundle "cron-bundle" from shapecode vendor doesn't manage the order. There is no order sequence column set in the table cron_job. The order is the one by default in the table cron_job, so the order of creation.

The only order you can change is the one set by Myddleware in the table ruleorder. However this sequence is calculated depending on the relationship between all the rules. For example, if you have a rule account and a rule contacts (linked to the account rule), the rule account is the higest level so it will always be run before the contacts rule. This order is only used if you run the command synchro ALL (it runs all active rules). You can manually change the order in this table. However, it will be recalculated each time you edit a rule, except if you redefine the standard code.

So if you need to set manually an sequence order in the job, we will have to develop this feature in Myddleware.

Please let me know if it answer your question.

**Comment by Myddleware** [comment]
I forgot to tell you sorry for the delay of our answer ;(

**Comment by simonetravaglini** [comment]
@Myddleware thanks for clarification.
Maybe an option could be give the possibility to use, like in M2, also scheduler function.
So with scheduler you set rules with priority and also many option you can use like before.
Crontask shuold work "in addition", and you can use if you need to set a rules in a more advanced way.
Do you think could be possible?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Thanks for your message.  I understand your point of view. However I think it will be confusing if we add a crontask runs by the cron-bundle which is run by the Linux crontab.

We have decided to use the cron-bundle because it will open new features for Myddleware. For example, you will soon be able to create a group of task (project). Then you will be able to run several projects in parallele. 

For example if you have several rules that connect Vtiger and a MSSQL database (project1), and another group of rules that connects Vtiger and Salesforce (project2), you will be able to synchronize both projects in the same time.
So it is very important for us to keep the bundle cron-bundle.

In your case, what we could do is adding the parameter "order" on each rules. If this parameter is empty then the default order calculated by Myddleware would be used. But if you set a parameter manually then your order will override the one calculated by Myddleware.
But this order would be used only if you run the commands "myddleware:synchro ALL"
Do you think it would meet you needs ? 

Have a nice day,
Stephane

**Comment by simonetravaglini** [comment]
Hi stephane,
thanks for answer. It could work but there is a case we have to add, and should not be hard.
Suppose I have a set of rules that I want to run every 5 minutes. I create rules, set actives, add order, and activate a cron with run all. Then I need a rule that run one a day. I set a cron for that. But In this case, if rule is active, is run also with run all.
So a solution could be add in rules a flag RUN ALL ACTIVE, and run all work only with rules with run all with flag. Or something similar. What do you think about @Myddleware

**Comment by Myddleware** [comment]
That's a great idea @simonetravaglini ,
We have added the parameter "force" in Myddleware 3.1.8 (not yet released) to force to run a rule even if another task is running. Myddleware will be able to run several task in the same time.
I have changed a little bit the code, now force paramet will also allow to run an inactive rule : https://github.com/Myddleware/myddleware/commit/70ebab2fa7dfbee63fe201da4973b1c640c613dd

We plan to release Myddleware 3.1.8 next week. So once you will have installed Myddleware 3.1.8, you will be able to run an inactive rule by setting the parameter force to one in the synchro command.

Hope it helps.

**Comment by simonetravaglini** [comment]
@Myddleware Force it's a great idea! Also for the case I call a rule from API... Maybe you can consider instead of run at same time to create a queue... anyway the solution implemented seems to solve all cases! After release we will test!

**Comment by Myddleware** [comment]
Hi @simonetravaglini , yes force parameter is always set to true when a command is called form the API.
