### ISSUE TITLE
Failed to create document

### ISSUE THREAD

**Issue by rafaelb26-dv** [Myddleware/myddleware#851]
Hi @Myddleware, i create a default rule for prestashop-moodle, it created right, but now it keeps giving this error:
![error01](https://user-images.githubusercontent.com/85837915/201119151-474a7bb7-1610-4020-86ce-dfe8ab02189b.png)

Log:
![error02log](https://user-images.githubusercontent.com/85837915/201119188-c0f18916-b060-4eac-b6d0-c6285e89bf4f.png)

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
I guess that the field you have selected as reference date in the rule edit view (confirmation tab) isn't a date : 
![image](https://user-images.githubusercontent.com/11330301/201140584-1e636356-5d9a-435b-911d-b1962db47265.png)

If you want Myddleware to work properly, this field should be the date when the record is modified in the database. Here is an example for MySQL : 
![image](https://user-images.githubusercontent.com/11330301/201141277-fb7d25db-0305-41c3-bc08-e3fd68743a63.png)

This field is very important because Myddleware use it to select the data which will be read. Myddleware will read all records in your database that have the modified date greater than the rule reference date (that you can change) : 
![image](https://user-images.githubusercontent.com/11330301/201141722-2a3f2da3-0684-41d2-bd26-83b4f042345a.png)

Hope it will help you.

**Comment by rafaelb26-dv** [comment]
Hi @Myddleware, only have these options, which one is correct?
![error03](https://user-images.githubusercontent.com/85837915/201173171-66b10b8e-f35a-4674-954c-bd8f8be3b3f7.png)

**Comment by Myddleware** [comment]
It depends what you need, if you want %Myddleware to create data only, update data only or both to your application. We usually set Create and update data.

**Comment by rafaelb26-dv** [comment]
Hi @Myddleware , think it worked, but there was another error, I will open a new issue
