### ISSUE TITLE
getDocumentHistory must fix LIMIT to 1

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#852]
Many database derived connector suffert by undefined limit on query! I suggest to add the following line 

```php
        $read['limit'] = 1;
```

Into this function https://github.com/Myddleware/myddleware/blob/c4f59cd8ae275c735e03ad0961654dd9a4f95d15/src/Manager/DocumentManager.php#L1128

The mission of this function is to get data from a system for a specific record based on $searchQuery, in many case it look for ONE record. Than leaving any misunderstood, fix the LIMIT to "1" is good and safe. Also speed up the data retrieve.
If you don't set the limit, the database connector act as wide range query with 100 items by default:

https://github.com/Myddleware/myddleware/blob/c4f59cd8ae275c735e03ad0961654dd9a4f95d15/src/Solutions/database.php#L217

This was tested and works well.

cc @simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Thanks for this message and your idea you have shared.
We can't set the limit to 1 because, in some cases, the read could return several records even if there is a query parameter. For example in case of child relationship in Prestashop, Myddleware could read a read all order line items with a specific order id. If the order has several items, then the read function will return several records.

However, if you are not in this case, you can redefine your class and force the limit to 1. 

Hope it helps. Don't hesitate to re open this issue if you want to reply.
