### ISSUE TITLE
how to get product stock prstashop and set it in custom field in Suitecrm

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#88]
Hi all,
I'am back,
I have create a module in suitecrm with is own table.

![image](https://user-images.githubusercontent.com/7665521/38029227-9248c2c4-3295-11e8-9f29-8c74f0690def.png)

Now when I create a rule in Myddleware to get the stock in presta and put it in suiteCRM
I have the error "Warning: there is no data in the source server or fields in the target solution"

![image](https://user-images.githubusercontent.com/7665521/38029265-b016ee7a-3295-11e8-85a1-7ff012e75ec5.png)
Why ?

I use myddleware v2.2.3
Thanks a lot,

**Comment by Myddleware** [comment]
Hi Alexandre,
Sorry for the delay.
You are right, This module hasn't reference date and we have to add this information in the connector.
It will be fixed in the next version but if you want it fixed now, you can modify you Prestashop connector file (src\Myddleware\RegleBundle\Solutions\prestashop.php)  by adding this :
![prestashop_stock](https://user-images.githubusercontent.com/11330301/38099259-1fc286b4-3348-11e8-8079-d542076cf982.png)
 
Could you tell us if it is working properly for you ? Thanks.
Best regards.
